version: "3.6"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: sa
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lev4and.ru
      PGADMIN_DEFAULT_PASSWORD: sa
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin