version: '3.4'

services:
  newsaggregator.gateways.api:
    image: ${DOCKER_REGISTRY-}newsaggregatorgatewaysapi
    container_name: newsaggregator-gateways-api
    depends_on:
        - newsaggregator.news.api
        - newsaggregator.notification.api
        - newsaggregator.gateways.api.seq
    build:
      context: .
      dockerfile: src/Microservices/Gateways/NewsAggregator.Gateways.Api/Dockerfile
    networks:
      - newsaggregator-gateways-api-proxy
      - newsaggregator-news-api-proxy
      - newsaggregator-notification-api-proxy

  newsaggregator.news.api:
    image: ${DOCKER_REGISTRY-}newsaggregatornewsapi
    container_name: newsaggregator-news-api
    depends_on:
      # - selenium.hub
      - postgres
      - redis 
      - rabbitmq
      # - elasticsearch
      - newsaggregator.news.api.seq
    build:
      context: .
      dockerfile: src/Microservices/Services/News/NewsAggregator.News.Api/Dockerfile
    networks:
      - newsaggregator-news-api-proxy
      - selenium-hub-proxy
      - postgres-proxy
      - redis-proxy
      - rabbitmq-proxy
      - elasticsearch-proxy


  newsaggregator.news.mvc:
    image: ${DOCKER_REGISTRY-}newsaggregatornewsmvc
    container_name: newsaggregator-news-mvc
    depends_on:
      # - selenium.hub
      - postgres
      - redis
      # - elasticsearch
      - newsaggregator.news.mvc.seq
    build:
      context: .
      dockerfile: src/Microservices/Services/News/NewsAggregator.News.Mvc/Dockerfile
    networks:
      - newsaggregator-news-mvc-proxy
      - selenium-hub-proxy
      - postgres-proxy
      - redis-proxy
      - rabbitmq-proxy
      - elasticsearch-proxy 


  newsaggregator.news.parser:
    image: ${DOCKER_REGISTRY-}newsaggregatornewsparser
    container_name: newsaggregator-news-parser
    depends_on:
      - newsaggregator.news.api
      # - selenium.hub
      - redis
      - rabbitmq
      - newsaggregator.news.parser.seq
    build:
      context: .
      dockerfile: src/Microservices/Services/News/NewsAggregator.News.Parser/Dockerfile
    networks:
      - newsaggregator-news-parser-proxy
      - selenium-hub-proxy
      - redis-proxy
      - rabbitmq-proxy


  newsaggregator.news.searcher:
    image: ${DOCKER_REGISTRY-}newsaggregatornewssearcher
    container_name: newsaggregator-news-searcher
    depends_on:
      - newsaggregator.news.api
      # - selenium.hub
      - redis
      - rabbitmq
      - newsaggregator.news.searcher.seq
    build:
      context: .
      dockerfile: src/Microservices/Services/News/NewsAggregator.News.Searcher/Dockerfile
    networks:
      - newsaggregator-news-searcher-proxy
      - selenium-hub-proxy
      - redis-proxy
      - rabbitmq-proxy

  newsaggregator.notification.api:
    image: ${DOCKER_REGISTRY-}newsaggregatornotificationapi
    container_name: newsaggregator-notification-api
    depends_on:
      - rabbitmq
      - newsaggregator.notification.api.seq
    build:
      context: .
      dockerfile: src/Microservices/Services/Notification/NewsAggregator.Notification.Api/Dockerfile
    networks:
      - newsaggregator-notification-api-proxy
      - rabbitmq-proxy
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
     - postgres-proxy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    networks:
      - rabbitmq-proxy

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    networks:
      - redis-proxy
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
  #   container_name: elasticsearch
  #   networks:
  #     - elasticsearch-proxy

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.1
  #   container_name: kibana
  #   links:
  #     - elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elasticsearch-proxy 

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.12.1
  #   container_name: logstash
  #   links:
  #     - elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elasticsearch-proxy
  
  # chrome:
  #   image: selenium/node-chrome:dev
  #   container_name: chrome
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium.hub
  #   networks:
  #     - selenium-hub-proxy

  # selenium.hub:
  #   image: selenium/hub:latest
  #   container_name: selenium-hub
  #   networks:
  #     - selenium-hub-proxy

  newsaggregator.gateways.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-gateways-api-seq
    networks:
      - newsaggregator-gateways-api-proxy
  
  newsaggregator.news.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-api-seq
    networks:
      - newsaggregator-news-api-proxy
  
  newsaggregator.news.mvc.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-mvc-seq
    networks:
      - newsaggregator-news-mvc-proxy
  
  newsaggregator.news.parser.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-parser-seq
    networks:
      - newsaggregator-news-parser-proxy
  
  newsaggregator.news.searcher.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-searcher-seq
    networks:
      - newsaggregator-news-searcher-proxy
 
  newsaggregator.notification.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-notification-api-seq
    networks:
      - newsaggregator-notification-api-proxy

networks:
  newsaggregator-gateways-api-proxy:
    driver: bridge
  newsaggregator-news-api-proxy:
    driver: bridge
  newsaggregator-news-mvc-proxy:
    driver: bridge
  newsaggregator-news-parser-proxy:
    driver: bridge
  newsaggregator-news-searcher-proxy:
    driver: bridge
  newsaggregator-notification-api-proxy:
    driver: bridge
  selenium-hub-proxy:
    driver: bridge 
  postgres-proxy:
    driver: bridge
  redis-proxy:
    driver: bridge
  rabbitmq-proxy:
    driver: bridge
  elasticsearch-proxy:
    driver: bridge


