version: '3.4'

services:
  newsaggregator.gateways.api:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-gateways-api:dev
    container_name: newsaggregator-gateways-api
    depends_on:
        - newsaggregator.news.api
        - newsaggregator.notification.api
        - newsaggregator.gateways.api.seq
    networks:
      - newsaggregator-gateways-api-proxy
      - newsaggregator-news-api-proxy
      - newsaggregator-notification-api-proxy
      - nginx-proxy

  newsaggregator.news.api:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-news-api:dev
    container_name: newsaggregator-news-api
    depends_on:
      - selenium.hub
      - postgres
      - redis 
      - rabbitmq
      # - elasticsearch
      - newsaggregator.news.api.seq
    networks:
      - newsaggregator-news-api-proxy
      - selenium-hub-proxy
      - postgres-proxy
      - redis-proxy
      - rabbitmq-proxy
      - elasticsearch-proxy
      - nginx-proxy


  newsaggregator.news.mvc:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-news-mvc:dev
    container_name: newsaggregator-news-mvc
    depends_on:
      - selenium.hub
      - postgres
      - redis
      # - elasticsearch
      - newsaggregator.news.mvc.seq
    networks:
      - newsaggregator-news-mvc-proxy
      - selenium-hub-proxy
      - postgres-proxy
      - redis-proxy
      - rabbitmq-proxy
      - elasticsearch-proxy 
      - nginx-proxy


  newsaggregator.news.parser:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-news-parser:dev
    container_name: newsaggregator-news-parser
    depends_on:
      - newsaggregator.news.api
      - selenium.hub
      - redis
      - rabbitmq
      - newsaggregator.news.parser.seq
    networks:
      - newsaggregator-news-parser-proxy
      - selenium-hub-proxy
      - redis-proxy
      - rabbitmq-proxy


  newsaggregator.news.searcher:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-news-searcher:dev
    container_name: newsaggregator-news-searcher
    depends_on:
      - newsaggregator.news.api
      - selenium.hub
      - redis
      - rabbitmq
      - newsaggregator.news.searcher.seq
    networks:
      - newsaggregator-news-searcher-proxy
      - selenium-hub-proxy
      - redis-proxy
      - rabbitmq-proxy

  newsaggregator.notification.api:
    image: ghcr.io/lev4and/newsaggregator/newsaggregator-notification-api:dev
    container_name: newsaggregator-notification-api
    depends_on:
      - rabbitmq
      - newsaggregator.notification.api.seq
    networks:
      - newsaggregator-notification-api-proxy
      - rabbitmq-proxy
      - nginx-proxy
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - postgres-proxy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always
    networks:
      - nginx-proxy
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    networks:
      - rabbitmq-proxy
      - nginx-proxy

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    networks:
      - redis-proxy
      - nginx-proxy
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
  #   container_name: elasticsearch
  #   networks:
  #     - elasticsearch-proxy
  #     - nginx-proxy

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.1
  #   container_name: kibana
  #   links:
  #     - elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elasticsearch-proxy
  #     - nginx-proxy
  
  chrome:
    image: selenium/node-chrome:dev
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium.hub
    networks:
      - selenium-hub-proxy
      - nginx-proxy

  selenium.hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - selenium-hub-proxy
      - nginx-proxy

  newsaggregator.gateways.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-gateways-api-seq
    networks:
      - newsaggregator-gateways-api-proxy
      - nginx-proxy
  
  newsaggregator.news.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-api-seq
    networks:
      - newsaggregator-news-api-proxy
      - nginx-proxy
  
  newsaggregator.news.mvc.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-mvc-seq
    networks:
      - newsaggregator-news-mvc-proxy
      - nginx-proxy
  
  newsaggregator.news.parser.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-parser-seq
    networks:
      - newsaggregator-news-parser-proxy
      - nginx-proxy
  
  newsaggregator.news.searcher.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-news-searcher-seq
    networks:
      - newsaggregator-news-searcher-proxy
      - nginx-proxy
 
  newsaggregator.notification.api.seq:
    image: datalust/seq:latest
    container_name: newsaggregator-notification-api-seq
    networks:
      - newsaggregator-notification-api-proxy
      - nginx-proxy

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    networks:
      - nginx-proxy

  node.exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - node-exporter-proxy
      - nginx-proxy
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - prometheus-proxy
      - nginx-proxy

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - node-exporter-proxy
      - prometheus-proxy
      - nginx-proxy

  nginx:
    image: nginx:mainline
    container_name: nginx
    depends_on:
        - newsaggregator.gateways.api
        - newsaggregator.gateways.api.seq
        - newsaggregator.news.api
        - newsaggregator.news.api.seq
        - newsaggregator.news.mvc
        - newsaggregator.news.parser
        - newsaggregator.news.parser.seq
        - newsaggregator.news.searcher
        - newsaggregator.news.searcher.seq
        - newsaggregator.notification.api
        - newsaggregator.notification.api.seq
        - pgadmin
        - rabbitmq 
        - redis
        - selenium.hub
        - portainer
        - grafana
    networks:
      - nginx-proxy

networks:
  newsaggregator-gateways-api-proxy:
    driver: bridge
  newsaggregator-news-api-proxy:
    driver: bridge
  newsaggregator-news-mvc-proxy:
    driver: bridge
  newsaggregator-news-parser-proxy:
    driver: bridge
  newsaggregator-news-searcher-proxy:
    driver: bridge
  newsaggregator-notification-api-proxy:
    driver: bridge
  selenium-hub-proxy:
    driver: bridge 
  postgres-proxy:
    driver: bridge
  redis-proxy:
    driver: bridge
  rabbitmq-proxy:
    driver: bridge
  elasticsearch-proxy:
    driver: bridge
  node-exporter-proxy:
    driver: bridge
  prometheus-proxy:
    driver: bridge
  nginx-proxy:
    driver: bridge