// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAggregator.News.Databases.EntityFramework.News;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsAggregator.News.Databases.EntityFramework.News.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20240119183235_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_news_editor_id");

                    b.HasIndex("Url", "Title")
                        .HasDatabaseName("ix_news_url_title");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_news_descriptions");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_descriptions_news_id");

                    b.ToTable("news_descriptions", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_editors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_news_editors_name");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_news_editors_source_id");

                    b.ToTable("news_editors", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("NameXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_x_path");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_editor_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_editor_settings_parse_settings_id");

                    b.ToTable("news_parse_editor_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3479b22-2254-40cf-a2a4-1aa89931ab96"),
                            IsRequired = false,
                            NameXPath = "//div[@class='topic-authors']/a[@class='topic-authors__author']/text()",
                            ParseSettingsId = new Guid("21bb13d0-526d-4219-a28d-524d20b5442f")
                        },
                        new
                        {
                            Id = new Guid("0a319d19-f39b-45b9-9e83-941883a5d3e6"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'PageArticleContent_authors')]//a[contains(@class, 'LinksOfAuthor_item')]/text()",
                            ParseSettingsId = new Guid("054410f0-c56e-4c17-b1e7-8120ad59ef8f")
                        },
                        new
                        {
                            Id = new Guid("8b95f193-ec0b-4a25-bb86-a99f5c9fe456"),
                            IsRequired = false,
                            NameXPath = "//div[@class='article_top']//div[@class='authors']//div[@class='autor']//span/text()",
                            ParseSettingsId = new Guid("df5dd5db-92ab-4b6b-8245-da3fbb28f055")
                        },
                        new
                        {
                            Id = new Guid("8f5fb7e3-1050-4256-87f9-15023acaef86"),
                            IsRequired = false,
                            NameXPath = "//div[@class='article__authors']//span[@class='article__authors__author']/span[@class='article__authors__author__name']/text()",
                            ParseSettingsId = new Guid("c7b1282c-ec2a-4174-80dd-d6a4a27d4443")
                        },
                        new
                        {
                            Id = new Guid("903003d5-15d2-42c8-9e8d-7a08b8897efd"),
                            IsRequired = false,
                            NameXPath = "//footer[@class='news-item__footer']/div[@class='news-item__footer-after-news']/p[position()=1]//span/text()",
                            ParseSettingsId = new Guid("98b0648b-309b-4fc2-a612-5c9a34d67e12")
                        },
                        new
                        {
                            Id = new Guid("e064c35c-44e4-4d7e-910e-55ce781d1635"),
                            IsRequired = false,
                            NameXPath = "//p[@class='doc__text document_authors']/text()",
                            ParseSettingsId = new Guid("2855d318-af0b-454e-8c7b-a54e7cf9cd31")
                        },
                        new
                        {
                            Id = new Guid("03155581-c7af-429f-95df-ddfb18c09ff4"),
                            IsRequired = false,
                            NameXPath = "//a[@class='article__author']/text()",
                            ParseSettingsId = new Guid("7f7819b0-75f5-4306-9018-d2302d5d36da")
                        },
                        new
                        {
                            Id = new Guid("399f19b8-e86f-41c4-83c5-a6c522ae682e"),
                            IsRequired = false,
                            NameXPath = "//article//header//div[@class='article-head__author-name']/a[@rel='author']/span/text()",
                            ParseSettingsId = new Guid("319b201e-1df9-4b48-b2c1-5dc939d0697d")
                        },
                        new
                        {
                            Id = new Guid("74170964-16cf-42cc-b221-15e023bcfe9f"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'styles_bodyWrapper')]//div[contains(@class, 'styles_authorsLinks')]/a/text()",
                            ParseSettingsId = new Guid("ee6767cd-b93f-48ae-96d1-0745548f1211")
                        },
                        new
                        {
                            Id = new Guid("d15ef936-a841-4d2e-848f-15ec47fd6d5b"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']//a[@itemprop='author']//span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("7d56b5ea-757e-4892-bbf1-f1a1e8a68df8")
                        },
                        new
                        {
                            Id = new Guid("b6b3dcea-ac58-4760-a807-24e6741031f9"),
                            IsRequired = false,
                            NameXPath = "//span[@itemprop='author']/span[@itemprop='name']/@content",
                            ParseSettingsId = new Guid("ed08b073-6c6d-4f23-b6f4-319eda95e90c")
                        },
                        new
                        {
                            Id = new Guid("5b15a604-dcf8-4596-a3f5-e62b9d528e96"),
                            IsRequired = false,
                            NameXPath = "//div[@class='container-fluid publication-footer']//a[contains(@class, 'text-secondary')]/@title",
                            ParseSettingsId = new Guid("33bf742f-b9f9-4a0c-9be0-b4531e62d91f")
                        },
                        new
                        {
                            Id = new Guid("d6f0986f-f8a6-4c0c-951c-651d4baedf30"),
                            IsRequired = false,
                            NameXPath = "//div[@class='author']/span[@itemprop='author']/span[@itemprop='name']/a/text()",
                            ParseSettingsId = new Guid("9bff4cd2-8967-4dd2-b8bd-4523bca2b389")
                        },
                        new
                        {
                            Id = new Guid("d1b5ec78-b614-4100-85fc-53b7a4142c69"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'full-article')]/div[@class='authors-block']//span[text()='Автор']/../a/text()",
                            ParseSettingsId = new Guid("b39299f9-1927-4a06-9101-a9eb44fc7d33")
                        },
                        new
                        {
                            Id = new Guid("e2f250c9-a7d9-40d1-abee-dc58bfdae6b4"),
                            IsRequired = false,
                            NameXPath = "//div[@itemprop='author']/span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("da8fdc18-5867-4b6a-8867-3f23a385b47d")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("UrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_picture_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_picture_settings_parse_settings_id");

                    b.ToTable("news_parse_picture_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ccaccf5-4572-4a32-bb0a-da31e3e78ec8"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b3dad0c5-1a66-4b9e-91e3-bb5c1a33f6d0"),
                            UrlXPath = "//div[@class='photoview__open']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("545a672f-dbf8-4b02-8f31-b8ddcc642034"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7d54652d-72ba-4c4f-afc2-6f5e9f56f071"),
                            UrlXPath = "//div[contains(@class, 'HeaderMedia_image')]//img[contains(@class, 'Image_image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("7cc2a8ec-3a2e-4409-94a6-3d15f0d0d809"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("21bb13d0-526d-4219-a28d-524d20b5442f"),
                            UrlXPath = "//div[contains(@class, 'topic-body__title-image')]//img[contains(@class, 'picture__image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("6facaa5b-ab4a-40a5-bc81-c812ebe785bf"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("df5dd5db-92ab-4b6b-8245-da3fbb28f055"),
                            UrlXPath = "//div[@class='img_box']/a[@class='zoom_js']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("328f80ee-64f0-49cd-9631-2faabafe7990"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("6ace34ff-46ab-461e-beb3-32c8ea8de4ff"),
                            UrlXPath = "//div[contains(@class, 'big_photo')]//div[@class='big_photo__img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("fa660b7a-6a2c-486a-98b0-cd792fd7205f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7f7819b0-75f5-4306-9018-d2302d5d36da"),
                            UrlXPath = "//div[@class='article__media']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("4ab52500-314c-4e4f-b217-f996c17d8dda"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("885073d1-e496-4cb1-ad62-0557e55b6b7b"),
                            UrlXPath = "//div[@class='inner_content']//div[@class='main_img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("da55894f-5373-4ee8-8e3d-999aa01b5ae6"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("355f72fb-f68d-4703-bb7c-3cdeb3aa986d"),
                            UrlXPath = "//div[@class='b-material-incut-m-image']//@src"
                        },
                        new
                        {
                            Id = new Guid("1492bce5-b89d-4d6c-9fed-a4400ec88330"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b5cba261-d4c2-430e-9476-c292ca02ea15"),
                            UrlXPath = "//article/figure/img/@src"
                        },
                        new
                        {
                            Id = new Guid("77a8a75d-5c4f-4157-b841-6f9fde5fa959"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("319b201e-1df9-4b48-b2c1-5dc939d0697d"),
                            UrlXPath = "//article//header/div[@class='article-head__photo']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("383f6fa0-821e-4a12-af67-4f080db419ee"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("ee6767cd-b93f-48ae-96d1-0745548f1211"),
                            UrlXPath = "//article//header/div[contains(@class, 'styles_cover_media')]/img/@src"
                        },
                        new
                        {
                            Id = new Guid("b26bc651-7475-4729-acec-1a65c3ace9b8"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7d56b5ea-757e-4892-bbf1-f1a1e8a68df8"),
                            UrlXPath = "//div[contains(@class, 'article-entry')]//div[contains(@class, 'entry-body')]//div[@class='source-wrapper']/img[@itemprop='image']/@src"
                        },
                        new
                        {
                            Id = new Guid("02f2ac17-d75e-4334-8c03-2a4eb1f0c3d2"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("33bf742f-b9f9-4a0c-9be0-b4531e62d91f"),
                            UrlXPath = "//a[@class='glightbox']/img[contains(@class, 'pub-cover')]/@src"
                        },
                        new
                        {
                            Id = new Guid("24c01f1c-fc44-4051-8f73-e69a709f2691"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("9bff4cd2-8967-4dd2-b8bd-4523bca2b389"),
                            UrlXPath = "//div[@class='b_article-media']//div[@class='mainarea-wrapper']/figure/img[@class='item-image-front']/@src"
                        },
                        new
                        {
                            Id = new Guid("84702fd3-11d2-4b58-b59e-723ac3997d9d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b39299f9-1927-4a06-9101-a9eb44fc7d33"),
                            UrlXPath = "//div[contains(@class, 'full-article')]/div[contains(@class, 'gallery')]/picture/img/@src"
                        },
                        new
                        {
                            Id = new Guid("19d2a7df-6ba3-4e15-9900-e2b74092bcc3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("da8fdc18-5867-4b6a-8867-3f23a385b47d"),
                            UrlXPath = "//div[@itemprop='articleBody']//div[@itemprop='image']/picture/img[@itemprop='contentUrl']/@src"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("PublishedAtCultureInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_culture_info");

                    b.Property<string>("PublishedAtFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_format");

                    b.Property<string>("PublishedAtXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_published_at_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_published_at_settings_parse_settings_id");

                    b.ToTable("news_parse_published_at_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cd49084-a893-44fd-b8b5-22864e35dfa9"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b3dad0c5-1a66-4b9e-91e3-bb5c1a33f6d0"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm dd.MM.yyyy",
                            PublishedAtXPath = "//div[@class='article__info']//div[@class='article__info-date']/a/text()"
                        },
                        new
                        {
                            Id = new Guid("508d0219-e865-4089-87dd-c5a422a2fb7f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1ac16379-85fc-4471-91bf-4fba750b8adb"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-d HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'article__date-autor-shortcode')]/div[contains(@class, 'article__date')]/time[@class='date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("a292ad5c-6949-40fe-8f08-c3c112a583df"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("21bb13d0-526d-4219-a28d-524d20b5442f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm, dd MMMM yyyy",
                            PublishedAtXPath = "//div[@class='topic-page__header']//a[contains(@class, 'topic-header__time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("3573af63-3403-4a61-a58d-069c45223ac7"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("054410f0-c56e-4c17-b1e7-8120ad59ef8f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'PageArticleContent_date')]/text()"
                        },
                        new
                        {
                            Id = new Guid("e87af2cb-a18f-492c-bdbd-e9410f0f28d0"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("df5dd5db-92ab-4b6b-8245-da3fbb28f055"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[@class='article_top']//div[@class='date']//time/text()"
                        },
                        new
                        {
                            Id = new Guid("74174195-fb9b-4c24-a37d-8fa0eee0681b"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c7b1282c-ec2a-4174-80dd-d6a4a27d4443"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='article__header__info-block']/time[@class='article__header__date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("6b5b23ec-4870-48a3-9295-77fcd9a3a19a"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("98b0648b-309b-4fc2-a612-5c9a34d67e12"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//header[@class='news-item__header']//time/@content"
                        },
                        new
                        {
                            Id = new Guid("8f93d081-e1ed-4639-91c6-51c42edff171"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("2855d318-af0b-454e-8c7b-a54e7cf9cd31"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='doc_header__time']/time[@class='doc_header__publish_time']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("d14b1caf-82b2-488c-b489-3261bd7d4cd1"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("6ace34ff-46ab-461e-beb3-32c8ea8de4ff"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:ssZ",
                            PublishedAtXPath = "//div[@class='article_page__left__top__left']//div[@class='article_page__left__top__time']//time/@datetime"
                        },
                        new
                        {
                            Id = new Guid("c04e1a29-25d4-4eec-b95c-9db4a65682f3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("885073d1-e496-4cb1-ad62-0557e55b6b7b"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd MMMM yyyy, HH:mm",
                            PublishedAtXPath = "//div[@class='date_full']/text()"
                        },
                        new
                        {
                            Id = new Guid("b1e1af9b-c413-4869-a7f7-aac46f879bb3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("355f72fb-f68d-4703-bb7c-3cdeb3aa986d"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm",
                            PublishedAtXPath = "//p[@class='b-material__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("58fa3ef1-898a-4011-b336-2533195d9d6f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b5cba261-d4c2-430e-9476-c292ca02ea15"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd MMMM yyyy, HH:mm",
                            PublishedAtXPath = "//article/div[@class='header']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("a50a3c6c-4209-4dd8-9222-e098a9085e4d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("319b201e-1df9-4b48-b2c1-5dc939d0697d"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd MMMM yyyy, HH:mm МСК",
                            PublishedAtXPath = "//article//header//time[@class='article-head__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("63182784-32c7-450c-89cc-a49af99b0ade"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7d56b5ea-757e-4892-bbf1-f1a1e8a68df8"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']/span[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("c23752cc-ec87-443f-9aa6-23e8db90a454"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("ed08b073-6c6d-4f23-b6f4-319eda95e90c"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd MMMM yyyy в HH:mm",
                            PublishedAtXPath = "//div[@class='b-article__top-author']/p[@class='date']/text()"
                        },
                        new
                        {
                            Id = new Guid("310f03b3-884a-4e78-b370-d051ca8abd63"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("33bf742f-b9f9-4a0c-9be0-b4531e62d91f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-dd HH:mm:ss",
                            PublishedAtXPath = "//div[contains(@class, 'publication-footer')]//div[contains(@class, 'pubdatetime')]//div[contains(@class, 'badge-time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("5759c1e0-1900-41c4-b992-e890fa19e1b5"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("9bff4cd2-8967-4dd2-b8bd-4523bca2b389"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//article/div[@class='b_article-header']//time[@itemprop='datePublished']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("99b0b8cc-d1e1-4f86-96bc-64624549e721"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d7851c41-54a0-40df-8fb7-1dd2827a7081"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:ss",
                            PublishedAtXPath = "//article[@itemprop='articleBody']/meta[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("6310c276-5ae3-4f72-a008-78ce666dbd2d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b39299f9-1927-4a06-9101-a9eb44fc7d33"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'full-article')]//time/text()"
                        },
                        new
                        {
                            Id = new Guid("37fe0495-0b77-42a9-8b17-5e7d66b3b9fc"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("da8fdc18-5867-4b6a-8867-3f23a385b47d"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='publication-info']/time[@itemprop='datePublished']/@datetime"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_settings_source_id");

                    b.ToTable("news_parse_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3dad0c5-1a66-4b9e-91e3-bb5c1a33f6d0"),
                            DescriptionXPath = "//div[contains(@class, 'article__body')]",
                            SourceId = new Guid("7bc22a9a-d7c9-4f46-9d06-9089973dc8c1"),
                            TitleXPath = "//div[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("1ac16379-85fc-4471-91bf-4fba750b8adb"),
                            DescriptionXPath = "//div[contains(@class, 'article__text ')]",
                            SourceId = new Guid("1dd832b4-d648-4cc1-a66d-dc4a1aeb2d3e"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("7d54652d-72ba-4c4f-afc2-6f5e9f56f071"),
                            DescriptionXPath = "//article",
                            SourceId = new Guid("26b6aa23-ec5a-4c2d-82e5-df6c4281840c"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("21bb13d0-526d-4219-a28d-524d20b5442f"),
                            DescriptionXPath = "//div[@class='topic-body__content']",
                            SourceId = new Guid("4281d39b-6c67-4694-8051-80c8bfb42c85"),
                            TitleXPath = "//h1[@class='topic-body__titles']/span[@class='topic-body__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("054410f0-c56e-4c17-b1e7-8120ad59ef8f"),
                            DescriptionXPath = "//div[contains(@class, 'PageContentCommonStyling_text')]",
                            SourceId = new Guid("8176977e-0609-4039-9817-13ebd4a594c0"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("df5dd5db-92ab-4b6b-8245-da3fbb28f055"),
                            DescriptionXPath = "//div[@class='article_text']",
                            SourceId = new Guid("1621dab4-8884-47d4-9d6a-d5ed618bad9d"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("c7b1282c-ec2a-4174-80dd-d6a4a27d4443"),
                            DescriptionXPath = "//div[@class='article__text article__text_free']/*[not(contains(@class, 'article__text__overview'))]",
                            SourceId = new Guid("1b727884-b599-46ea-9559-f5ac8df72b37"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("98b0648b-309b-4fc2-a612-5c9a34d67e12"),
                            DescriptionXPath = "//div[contains(@class, 'news-item__content')]",
                            SourceId = new Guid("315e5042-c21f-4a97-8f5a-f85353e6b843"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("2855d318-af0b-454e-8c7b-a54e7cf9cd31"),
                            DescriptionXPath = "//div[@class='article_text_wrapper js-search-mark']/*[not(contains(@class, 'doc__text document_authors'))]",
                            SourceId = new Guid("0666d8fe-3a01-484a-9545-f18043e2fdc7"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("6ace34ff-46ab-461e-beb3-32c8ea8de4ff"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("423fb2ef-6fbb-4dba-aa42-a3a4e56ab9bc"),
                            TitleXPath = "//h1/span/text()"
                        },
                        new
                        {
                            Id = new Guid("7f7819b0-75f5-4306-9018-d2302d5d36da"),
                            DescriptionXPath = "//div[@class='article__content']/*[not(contains(@class, 'article__title')) and not(contains(@class, 'article__intro'))]",
                            SourceId = new Guid("dababa54-577a-4781-9b5d-22e58a926c41"),
                            TitleXPath = "//h1[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("885073d1-e496-4cb1-ad62-0557e55b6b7b"),
                            DescriptionXPath = "//div[@class='js-mediator-article']",
                            SourceId = new Guid("e51842f9-c29b-4a8f-95e5-27d9ef08c722"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("a9427434-9305-41ff-98da-9f5c6e28cde9"),
                            DescriptionXPath = "//div[@class='b-text__content']/div[contains(@class, 'b-text__block')]",
                            SourceId = new Guid("fdbffa3f-d8a5-457b-aee2-33d98d4e994d"),
                            TitleXPath = "//h1[@class='b-text__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("355f72fb-f68d-4703-bb7c-3cdeb3aa986d"),
                            DescriptionXPath = "//div[@class='b-material-body']/div/*[not(@class='b-material-incut-m-image')]",
                            SourceId = new Guid("1d01237e-5703-4dd4-b656-ed8d8455fca9"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("b5cba261-d4c2-430e-9476-c292ca02ea15"),
                            DescriptionXPath = "//article/div[@class='news_text']",
                            SourceId = new Guid("274c593b-e765-4e43-bf3b-ad8b3fde7f22"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("319b201e-1df9-4b48-b2c1-5dc939d0697d"),
                            DescriptionXPath = "//article/div[@class='article-content']/*[not(@class)]",
                            SourceId = new Guid("2cedf7b3-a21e-4a44-9c39-e272ad58633e"),
                            TitleXPath = "//article/header/div[@class='article-head__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("ee6767cd-b93f-48ae-96d1-0745548f1211"),
                            DescriptionXPath = "//div[contains(@class, 'styles_bodyWrapper')]/div[not(@class)]",
                            SourceId = new Guid("c44824c3-3012-48ec-a41a-447a03bcd7c7"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("7d56b5ea-757e-4892-bbf1-f1a1e8a68df8"),
                            DescriptionXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()>1]",
                            SourceId = new Guid("29f02fb2-a812-463f-aea3-5349fa7eb20a"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("ed08b073-6c6d-4f23-b6f4-319eda95e90c"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("6869b0a0-a535-4618-aced-9b2fcf4e516d"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("33bf742f-b9f9-4a0c-9be0-b4531e62d91f"),
                            DescriptionXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']",
                            SourceId = new Guid("b779773d-2ce6-43f9-87f2-a09fa52bbde8"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("9bff4cd2-8967-4dd2-b8bd-4523bca2b389"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("ffedc8a3-77db-48a4-8c2e-cab85b7695cb"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("d7851c41-54a0-40df-8fb7-1dd2827a7081"),
                            DescriptionXPath = "//article[@itemprop='articleBody']/*[not(name() = 'h1') and not(name() = 'aside') and not(name() = 'meta') and not(name() = 'link') and not(@itemprop)]",
                            SourceId = new Guid("84d97c47-99a6-4111-9105-a5b23e6e661c"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("b39299f9-1927-4a06-9101-a9eb44fc7d33"),
                            DescriptionXPath = "//div[contains(@class, 'full-article')]/*[not(name()='h1') and not(name()='style') and not(name()='div')]",
                            SourceId = new Guid("e0f83a79-a04e-4ea9-9d44-a5921b6ed4f4"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("da8fdc18-5867-4b6a-8867-3f23a385b47d"),
                            DescriptionXPath = "//div[@itemprop='articleBody']/*[not(name()='div')]",
                            SourceId = new Guid("28037fc3-f074-440a-95e5-2e1ed370269e"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_sub_title_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_sub_title_settings_parse_settings_id");

                    b.ToTable("news_parse_sub_title_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58126330-8f36-4122-89f0-dfd1915ffe7f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b3dad0c5-1a66-4b9e-91e3-bb5c1a33f6d0"),
                            TitleXPath = "//h1[@class='article__second-title']/text()"
                        },
                        new
                        {
                            Id = new Guid("a1a653f4-3d2e-4215-89af-4a70a4368d0f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1ac16379-85fc-4471-91bf-4fba750b8adb"),
                            TitleXPath = "//div[contains(@class, 'article__summary')]/text()"
                        },
                        new
                        {
                            Id = new Guid("97a80552-f544-4845-8c19-a8969123111b"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7d54652d-72ba-4c4f-afc2-6f5e9f56f071"),
                            TitleXPath = "//h3/text()"
                        },
                        new
                        {
                            Id = new Guid("3b23800c-709f-4d74-afc6-427463fa5db4"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("21bb13d0-526d-4219-a28d-524d20b5442f"),
                            TitleXPath = "//div[contains(@class, 'topic-body__title')]/text()"
                        },
                        new
                        {
                            Id = new Guid("9eacd2ce-797f-475e-8783-7d8a0cd3b838"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("054410f0-c56e-4c17-b1e7-8120ad59ef8f"),
                            TitleXPath = "//div[contains(@class, 'PageArticleContent_lead')]/text()"
                        },
                        new
                        {
                            Id = new Guid("78af778c-c8dc-4864-8025-22366fd79d5e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c7b1282c-ec2a-4174-80dd-d6a4a27d4443"),
                            TitleXPath = "//div[contains(@class, 'article__text')]/div[@class='article__text__overview']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("a2456620-2035-4647-b795-82df01d35060"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("2855d318-af0b-454e-8c7b-a54e7cf9cd31"),
                            TitleXPath = "//header[@class='doc_header']/h2[contains(@class, 'doc_header__subheader')]/text()"
                        },
                        new
                        {
                            Id = new Guid("f1f9b647-ed97-4e5d-a36c-85c8df303dbc"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7f7819b0-75f5-4306-9018-d2302d5d36da"),
                            TitleXPath = "//div[@class='article__intro']/p/text()"
                        },
                        new
                        {
                            Id = new Guid("70377ef1-ced6-46b3-ae39-d1d881e67be7"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b5cba261-d4c2-430e-9476-c292ca02ea15"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("3627c6c0-070b-43ad-ba60-1af26ffe6100"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("ee6767cd-b93f-48ae-96d1-0745548f1211"),
                            TitleXPath = "//article//header//p[contains(@class, 'styles_subtitle')]/text()"
                        },
                        new
                        {
                            Id = new Guid("01acd26d-4ee4-4a7f-a864-b1d918b01375"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7d56b5ea-757e-4892-bbf1-f1a1e8a68df8"),
                            TitleXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()=1]/text()"
                        },
                        new
                        {
                            Id = new Guid("b7951ac4-5e83-4f55-bef5-91b4e184e816"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("ed08b073-6c6d-4f23-b6f4-319eda95e90c"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("6863bcda-3eec-4950-957c-3cae9ef8891c"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("33bf742f-b9f9-4a0c-9be0-b4531e62d91f"),
                            TitleXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']/text()"
                        },
                        new
                        {
                            Id = new Guid("25f01932-8585-4ee9-bf14-45cee19cb316"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("9bff4cd2-8967-4dd2-b8bd-4523bca2b389"),
                            TitleXPath = "//h2/text()"
                        },
                        new
                        {
                            Id = new Guid("666dfdd0-601a-46bc-93a5-5202f87dd82b"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b39299f9-1927-4a06-9101-a9eb44fc7d33"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_pictures");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_pictures_news_id");

                    b.ToTable("news_pictures", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NewsSiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_site_url");

                    b.Property<string>("NewsUrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_url_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_search_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_search_settings_source_id");

                    b.ToTable("news_search_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cc0a1f2-d80a-43b7-ae0d-78eb30f9cc1e"),
                            NewsSiteUrl = "https://ria.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'cell-list__item-link')]/@href",
                            SourceId = new Guid("7bc22a9a-d7c9-4f46-9d06-9089973dc8c1")
                        },
                        new
                        {
                            Id = new Guid("7e497b0f-3662-4dbc-8251-1b8dcfcd9b33"),
                            NewsSiteUrl = "https://russian.rt.com/",
                            NewsUrlXPath = "//a[contains(@class, 'link') and contains(@href, 'news/')]/@href",
                            SourceId = new Guid("1dd832b4-d648-4cc1-a66d-dc4a1aeb2d3e")
                        },
                        new
                        {
                            Id = new Guid("858075c0-4b5c-42ae-82e7-a010b388f9f0"),
                            NewsSiteUrl = "https://tass.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'tass_pkg_link-v5WdK') and contains(substring(@href, 2), '/')]/@href",
                            SourceId = new Guid("26b6aa23-ec5a-4c2d-82e5-df6c4281840c")
                        },
                        new
                        {
                            Id = new Guid("13e26c4a-78ca-4f15-a4f7-3551f5d52394"),
                            NewsSiteUrl = "https://lenta.ru/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/')]/@href",
                            SourceId = new Guid("4281d39b-6c67-4694-8051-80c8bfb42c85")
                        },
                        new
                        {
                            Id = new Guid("7d925f61-e600-4923-827e-a7da12b81d38"),
                            NewsSiteUrl = "https://rg.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html')]/@href",
                            SourceId = new Guid("8176977e-0609-4039-9817-13ebd4a594c0")
                        },
                        new
                        {
                            Id = new Guid("d2364498-2af7-408d-b0bd-607bdd820f26"),
                            NewsSiteUrl = "https://aif.ru/",
                            NewsUrlXPath = "//span[contains(@class, 'item_text__title')]/../@href",
                            SourceId = new Guid("1621dab4-8884-47d4-9d6a-d5ed618bad9d")
                        },
                        new
                        {
                            Id = new Guid("22ab0be9-df5d-403b-9138-65382b1cb628"),
                            NewsSiteUrl = "https://www.rbc.ru/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.rbc.ru/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("1b727884-b599-46ea-9559-f5ac8df72b37")
                        },
                        new
                        {
                            Id = new Guid("54466222-9e57-4432-a758-752f24f0eec5"),
                            NewsSiteUrl = "https://www.sports.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '.html#comments'))]/@href",
                            SourceId = new Guid("315e5042-c21f-4a97-8f5a-f85353e6b843")
                        },
                        new
                        {
                            Id = new Guid("395e4351-9f51-45fa-a190-d5c50e6059e0"),
                            NewsSiteUrl = "https://www.kommersant.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/doc/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("0666d8fe-3a01-484a-9545-f18043e2fdc7")
                        },
                        new
                        {
                            Id = new Guid("cee0a5b1-2640-4870-aa2b-07b7dc617181"),
                            NewsSiteUrl = "https://iz.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '?main_click')]/@href",
                            SourceId = new Guid("423fb2ef-6fbb-4dba-aa42-a3a4e56ab9bc")
                        },
                        new
                        {
                            Id = new Guid("83e2f343-4216-4544-9b49-af2568cafb34"),
                            NewsSiteUrl = "https://tsargrad.tv/",
                            NewsUrlXPath = "//a[contains(@class, 'news-item__link')]/@href",
                            SourceId = new Guid("dababa54-577a-4781-9b5d-22e58a926c41")
                        },
                        new
                        {
                            Id = new Guid("c6f73424-87f6-4452-b13b-7e586f3c4577"),
                            NewsSiteUrl = "https://www.belta.by/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.belta.by/') and contains(@href, '/view/')]/@href",
                            SourceId = new Guid("e51842f9-c29b-4a8f-95e5-27d9ef08c722")
                        },
                        new
                        {
                            Id = new Guid("6559ea43-32c2-4150-ba24-5ebaa43f717a"),
                            NewsSiteUrl = "https://svpressa.ru/all/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(contains(@href, '?')) and not(starts-with(@href, '/all/news/'))]/@href",
                            SourceId = new Guid("fdbffa3f-d8a5-457b-aee2-33d98d4e994d")
                        },
                        new
                        {
                            Id = new Guid("9bd27d44-7afc-4b20-b5f9-6fc285dd4f75"),
                            NewsSiteUrl = "https://www.m24.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("1d01237e-5703-4dd4-b656-ed8d8455fca9")
                        },
                        new
                        {
                            Id = new Guid("f2ce9828-5abb-4084-8084-270952d83103"),
                            NewsSiteUrl = "https://vz.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '#comments')) and not(contains(@href, '?')) and not(contains(@href, '/about/'))]/@href",
                            SourceId = new Guid("274c593b-e765-4e43-bf3b-ad8b3fde7f22")
                        },
                        new
                        {
                            Id = new Guid("c1115288-5f2e-48c5-981b-01eea9d02e6d"),
                            NewsSiteUrl = "https://www.championat.com/news/1.html?utm_source=button&utm_medium=news",
                            NewsUrlXPath = "//a[contains(@href, 'news-') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("2cedf7b3-a21e-4a44-9c39-e272ad58633e")
                        },
                        new
                        {
                            Id = new Guid("f2550085-7e4e-47f3-b7fe-f4be74c8de10"),
                            NewsSiteUrl = "https://life.ru/s/novosti",
                            NewsUrlXPath = "//a[contains(@href, '/p/')]/@href",
                            SourceId = new Guid("c44824c3-3012-48ec-a41a-447a03bcd7c7")
                        },
                        new
                        {
                            Id = new Guid("cea91ed3-2cba-43a2-8262-23f3c1a6e5d9"),
                            NewsSiteUrl = "https://3dnews.ru/news/",
                            NewsUrlXPath = "//div[@class='news-feed-all']//a[@class='entry-header']/h1/../@href",
                            SourceId = new Guid("29f02fb2-a812-463f-aea3-5349fa7eb20a")
                        },
                        new
                        {
                            Id = new Guid("f7dc868c-3902-48f8-9a20-b4beda389366"),
                            NewsSiteUrl = "https://www.ixbt.com/news/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("6869b0a0-a535-4618-aced-9b2fcf4e516d")
                        },
                        new
                        {
                            Id = new Guid("83d55012-160d-4996-b9fb-8a3d5401ab4f"),
                            NewsSiteUrl = "https://ixbt.games/news/",
                            NewsUrlXPath = "//a[@class='card-link']/@href",
                            SourceId = new Guid("b779773d-2ce6-43f9-87f2-a09fa52bbde8")
                        },
                        new
                        {
                            Id = new Guid("74a05ca6-10ed-4f56-9a9a-d05f17a2b768"),
                            NewsSiteUrl = "https://www.gazeta.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and contains(@href, '.shtml') and not(contains(@href, '?'))]/@href",
                            SourceId = new Guid("ffedc8a3-77db-48a4-8c2e-cab85b7695cb")
                        },
                        new
                        {
                            Id = new Guid("64021833-6e34-4bba-a314-226db8f2dfb8"),
                            NewsSiteUrl = "https://www.interfax.ru/",
                            NewsUrlXPath = "//div[@class='timeline']//a[@tabindex=5]/@href",
                            SourceId = new Guid("84d97c47-99a6-4111-9105-a5b23e6e661c")
                        },
                        new
                        {
                            Id = new Guid("4fba90b0-702b-470a-af7d-e2fadee476c1"),
                            NewsSiteUrl = "https://www.pravda.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(@href='https://www.pravda.ru/news/')]/@href",
                            SourceId = new Guid("e0f83a79-a04e-4ea9-9d44-a5921b6ed4f4")
                        },
                        new
                        {
                            Id = new Guid("30001825-59c1-45dc-be2f-a1ca2406c4ee"),
                            NewsSiteUrl = "https://ura.news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("28037fc3-f074-440a-95e5-2e1ed370269e")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sources");

                    b.HasIndex("Title", "SiteUrl", "IsEnabled")
                        .HasDatabaseName("ix_news_sources_title_site_url_is_enabled");

                    b.ToTable("news_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bc22a9a-d7c9-4f46-9d06-9089973dc8c1"),
                            IsEnabled = false,
                            SiteUrl = "https://ria.ru/",
                            Title = "РИА Новости"
                        },
                        new
                        {
                            Id = new Guid("1dd832b4-d648-4cc1-a66d-dc4a1aeb2d3e"),
                            IsEnabled = false,
                            SiteUrl = "https://russian.rt.com/",
                            Title = "RT на русском"
                        },
                        new
                        {
                            Id = new Guid("26b6aa23-ec5a-4c2d-82e5-df6c4281840c"),
                            IsEnabled = false,
                            SiteUrl = "https://tass.ru/",
                            Title = "ТАСС"
                        },
                        new
                        {
                            Id = new Guid("4281d39b-6c67-4694-8051-80c8bfb42c85"),
                            IsEnabled = false,
                            SiteUrl = "https://lenta.ru/",
                            Title = "Лента.Ру"
                        },
                        new
                        {
                            Id = new Guid("8176977e-0609-4039-9817-13ebd4a594c0"),
                            IsEnabled = false,
                            SiteUrl = "https://rg.ru/",
                            Title = "Российская газета"
                        },
                        new
                        {
                            Id = new Guid("1621dab4-8884-47d4-9d6a-d5ed618bad9d"),
                            IsEnabled = false,
                            SiteUrl = "https://aif.ru/",
                            Title = "Аргументы и факты"
                        },
                        new
                        {
                            Id = new Guid("1b727884-b599-46ea-9559-f5ac8df72b37"),
                            IsEnabled = false,
                            SiteUrl = "https://www.rbc.ru/",
                            Title = "РБК"
                        },
                        new
                        {
                            Id = new Guid("315e5042-c21f-4a97-8f5a-f85353e6b843"),
                            IsEnabled = false,
                            SiteUrl = "https://www.sports.ru/",
                            Title = "Storts.ru"
                        },
                        new
                        {
                            Id = new Guid("0666d8fe-3a01-484a-9545-f18043e2fdc7"),
                            IsEnabled = false,
                            SiteUrl = "https://www.kommersant.ru/",
                            Title = "Коммерсантъ"
                        },
                        new
                        {
                            Id = new Guid("423fb2ef-6fbb-4dba-aa42-a3a4e56ab9bc"),
                            IsEnabled = false,
                            SiteUrl = "https://iz.ru/",
                            Title = "Известия"
                        },
                        new
                        {
                            Id = new Guid("dababa54-577a-4781-9b5d-22e58a926c41"),
                            IsEnabled = false,
                            SiteUrl = "https://tsargrad.tv/",
                            Title = "Царьград"
                        },
                        new
                        {
                            Id = new Guid("e51842f9-c29b-4a8f-95e5-27d9ef08c722"),
                            IsEnabled = false,
                            SiteUrl = "https://www.belta.by/",
                            Title = "БелТА"
                        },
                        new
                        {
                            Id = new Guid("fdbffa3f-d8a5-457b-aee2-33d98d4e994d"),
                            IsEnabled = false,
                            SiteUrl = "https://svpressa.ru/",
                            Title = "СвободнаяПресса"
                        },
                        new
                        {
                            Id = new Guid("1d01237e-5703-4dd4-b656-ed8d8455fca9"),
                            IsEnabled = false,
                            SiteUrl = "https://www.m24.ru/",
                            Title = "Москва 24"
                        },
                        new
                        {
                            Id = new Guid("274c593b-e765-4e43-bf3b-ad8b3fde7f22"),
                            IsEnabled = false,
                            SiteUrl = "https://vz.ru/",
                            Title = "ВЗГЛЯД.РУ"
                        },
                        new
                        {
                            Id = new Guid("2cedf7b3-a21e-4a44-9c39-e272ad58633e"),
                            IsEnabled = false,
                            SiteUrl = "https://www.championat.com/",
                            Title = "Чемпионат.com"
                        },
                        new
                        {
                            Id = new Guid("c44824c3-3012-48ec-a41a-447a03bcd7c7"),
                            IsEnabled = false,
                            SiteUrl = "https://life.ru/",
                            Title = "Life"
                        },
                        new
                        {
                            Id = new Guid("29f02fb2-a812-463f-aea3-5349fa7eb20a"),
                            IsEnabled = false,
                            SiteUrl = "https://3dnews.ru/",
                            Title = "3Dnews.ru"
                        },
                        new
                        {
                            Id = new Guid("6869b0a0-a535-4618-aced-9b2fcf4e516d"),
                            IsEnabled = false,
                            SiteUrl = "https://www.ixbt.com/",
                            Title = "iXBT.com"
                        },
                        new
                        {
                            Id = new Guid("b779773d-2ce6-43f9-87f2-a09fa52bbde8"),
                            IsEnabled = false,
                            SiteUrl = "https://ixbt.games/",
                            Title = "iXBT.games"
                        },
                        new
                        {
                            Id = new Guid("ffedc8a3-77db-48a4-8c2e-cab85b7695cb"),
                            IsEnabled = false,
                            SiteUrl = "https://www.gazeta.ru/",
                            Title = "Газета.Ru"
                        },
                        new
                        {
                            Id = new Guid("84d97c47-99a6-4111-9105-a5b23e6e661c"),
                            IsEnabled = false,
                            SiteUrl = "https://www.interfax.ru/",
                            Title = "Интерфакс"
                        },
                        new
                        {
                            Id = new Guid("e0f83a79-a04e-4ea9-9d44-a5921b6ed4f4"),
                            IsEnabled = false,
                            SiteUrl = "https://www.pravda.ru/",
                            Title = "Правда.ру"
                        },
                        new
                        {
                            Id = new Guid("28037fc3-f074-440a-95e5-2e1ed370269e"),
                            IsEnabled = false,
                            SiteUrl = "https://ura.news/",
                            Title = "Ura.ru"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_source_logos");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_source_logos_source_id");

                    b.ToTable("news_source_logos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("460bf135-7741-469c-a1d8-b31935cd4293"),
                            SourceId = new Guid("b779773d-2ce6-43f9-87f2-a09fa52bbde8"),
                            Url = "https://sun13-2.userapi.com/s/v1/ig2/_ID-2w6Llad8ig5_987dKAfh1pyLdj7HfLHqGx9HxyDjoEDN7wxR0ZWJm5ja1Ey6UuQXaEYEBW1Zd51cpRrjSGfS.jpg?size=100x100&quality=96&crop=22,22,626,626&ava=1"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sub_titles");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_sub_titles_news_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_news_sub_titles_title");

                    b.ToTable("news_sub_titles", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", "Editor")
                        .WithMany("News")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_news_editors_editor_id");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Description")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_descriptions_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithMany("Editors")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_editors_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseEditorSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_editor_settings_news_parse_settings_parse_settin");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePictureSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_picture_settings_news_parse_settings_parse_setti");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePublishedAtSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_published_at_settings_news_parse_settings_parse_");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("ParseSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseSubTitleSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_sub_title_settings_news_parse_settings_parse_set");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Picture")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_pictures_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("SearchSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_search_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("Logo")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_source_logos_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("SubTitle")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_sub_titles_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Picture");

                    b.Navigation("SubTitle");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Navigation("ParseEditorSettings");

                    b.Navigation("ParsePictureSettings");

                    b.Navigation("ParsePublishedAtSettings");

                    b.Navigation("ParseSubTitleSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Navigation("Editors");

                    b.Navigation("Logo");

                    b.Navigation("ParseSettings");

                    b.Navigation("SearchSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
