// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAggregator.News.Databases.EntityFramework.News;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsAggregator.News.Databases.EntityFramework.News.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_news_editor_id");

                    b.HasIndex("Url", "Title")
                        .HasDatabaseName("ix_news_url_title");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_news_descriptions");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_descriptions_news_id");

                    b.ToTable("news_descriptions", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_editors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_news_editors_name");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_news_editors_source_id");

                    b.ToTable("news_editors", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("NameXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_x_path");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_editor_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_editor_settings_parse_settings_id");

                    b.ToTable("news_parse_editor_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("48cd30b8-2d88-430c-9bbf-8be673efcb7c"),
                            IsRequired = false,
                            NameXPath = "//div[@class='topic-authors']/a[@class='topic-authors__author']/text()",
                            ParseSettingsId = new Guid("774e9c7c-f642-465c-b93c-c2aacdf18b8f")
                        },
                        new
                        {
                            Id = new Guid("4a17666d-f9c0-4560-8137-a63de4025b2d"),
                            IsRequired = true,
                            NameXPath = "//div[contains(@class, 'PageArticleContent_authors')]//a[contains(@class, 'LinksOfAuthor_item')]/text()",
                            ParseSettingsId = new Guid("84393779-d9b0-44f7-a563-d44269ff77b2")
                        },
                        new
                        {
                            Id = new Guid("2fa87f8f-77e3-4a40-bb08-df1b179d08e4"),
                            IsRequired = true,
                            NameXPath = "//div[@class='article_top']//div[@class='authors']//div[@class='autor']//span/text()",
                            ParseSettingsId = new Guid("87b4be29-0d30-4a16-aa55-cfb56b544ec7")
                        },
                        new
                        {
                            Id = new Guid("55f828be-e945-4145-a0a5-cb6ef7b5400c"),
                            IsRequired = false,
                            NameXPath = "//div[@class='article__authors']//span[@class='article__authors__author']/span[@class='article__authors__author__name']/text()",
                            ParseSettingsId = new Guid("f80c5aa4-3026-4657-bb2b-90533ace23c5")
                        },
                        new
                        {
                            Id = new Guid("973da7aa-3331-4618-ac6c-acb2d90a99ec"),
                            IsRequired = true,
                            NameXPath = "//footer[@class='news-item__footer']/div[@class='news-item__footer-after-news']/p[position()=1]//span/text()",
                            ParseSettingsId = new Guid("4fb1ad7e-ee34-45b8-b81c-251d94b8ad1f")
                        },
                        new
                        {
                            Id = new Guid("412d8535-f413-480f-a59c-2ba581d417e6"),
                            IsRequired = false,
                            NameXPath = "//p[@class='doc__text document_authors']/text()",
                            ParseSettingsId = new Guid("5ea05fa3-4d71-49e7-8467-febe303b82b9")
                        },
                        new
                        {
                            Id = new Guid("789ee004-4d92-4cd0-bdfd-e4fcbd1d623f"),
                            IsRequired = true,
                            NameXPath = "//a[@class='article__author']/text()",
                            ParseSettingsId = new Guid("d3ff4b84-a0ff-4eb7-8ad4-9fbf56315c64")
                        },
                        new
                        {
                            Id = new Guid("43cce736-884f-4d68-9663-536d96a0ec4b"),
                            IsRequired = true,
                            NameXPath = "//article//header//div[@class='article-head__author-name']/a[@rel='author']/span/text()",
                            ParseSettingsId = new Guid("806fa257-eca5-419d-a26e-f1b7a3dcbcb3")
                        },
                        new
                        {
                            Id = new Guid("e71cc6e8-bb85-4a33-a607-08f825dc436f"),
                            IsRequired = true,
                            NameXPath = "//div[contains(@class, 'styles_bodyWrapper')]//div[contains(@class, 'styles_authorsLinks')]/a/text()",
                            ParseSettingsId = new Guid("f528a6df-4678-464b-9da9-97dd1b0b2fff")
                        },
                        new
                        {
                            Id = new Guid("a8dae2f3-ee5e-4f5e-a559-18869d7f24f8"),
                            IsRequired = true,
                            NameXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']//a[@itemprop='author']//span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("23d9436f-0d7b-40e3-957a-3a019c1dc109")
                        },
                        new
                        {
                            Id = new Guid("85d588cc-87f8-4413-a507-9dde93638303"),
                            IsRequired = true,
                            NameXPath = "//span[@itemprop='author']/span[@itemprop='name']/@content",
                            ParseSettingsId = new Guid("d6374200-a1cd-46cd-9f88-14c86ab30e08")
                        },
                        new
                        {
                            Id = new Guid("5b64aeff-1add-4819-9aa6-bdf2a03ca909"),
                            IsRequired = true,
                            NameXPath = "//div[@class='container-fluid publication-footer']//a[contains(@class, 'text-secondary')]/@title",
                            ParseSettingsId = new Guid("13982eaf-47d9-4d24-b9db-eb15c34e9940")
                        },
                        new
                        {
                            Id = new Guid("d4b3e185-c6d7-4964-a4b4-f13f7fc042db"),
                            IsRequired = false,
                            NameXPath = "//div[@class='author']/span[@itemprop='author']/span[@itemprop='name']/a/text()",
                            ParseSettingsId = new Guid("84135793-ab32-4867-8bf1-8147b2b3c14c")
                        },
                        new
                        {
                            Id = new Guid("dc00a41a-e9b1-49ca-b25b-ded7933f8af4"),
                            IsRequired = true,
                            NameXPath = "//div[contains(@class, 'full-article')]/div[@class='authors-block']//span[text()='Автор']/../a/text()",
                            ParseSettingsId = new Guid("8363a541-546f-4a17-8ca3-3a6f0f4aa6c6")
                        },
                        new
                        {
                            Id = new Guid("a170c6e0-44bd-4684-92e6-d644d10225a6"),
                            IsRequired = true,
                            NameXPath = "//div[@itemprop='author']/span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("77b72f9f-6883-4f7f-9a24-5aa83531a35a")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NewsUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_url");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_errors");

                    b.ToTable("news_parse_errors", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("UrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_picture_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_picture_settings_parse_settings_id");

                    b.ToTable("news_parse_picture_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcc659dd-d3d3-4717-b530-e78fc2e1d510"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c03dfd86-0f2e-4c0a-87d3-26d61263c773"),
                            UrlXPath = "//div[@class='photoview__open']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("b1ffceab-f195-413d-b99c-7257a62b35ff"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("e2be7c42-b23a-4849-b382-065f32cc9da6"),
                            UrlXPath = "//div[contains(@class, 'HeaderMedia_image')]//img[contains(@class, 'Image_image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("cd065e66-b428-4c3b-bb32-fa52be511b44"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("774e9c7c-f642-465c-b93c-c2aacdf18b8f"),
                            UrlXPath = "//div[contains(@class, 'topic-body__title-image')]//img[contains(@class, 'picture__image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("26111aba-b289-46db-8659-fcc4b7cc49ad"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("87b4be29-0d30-4a16-aa55-cfb56b544ec7"),
                            UrlXPath = "//div[@class='img_box']/a[@class='zoom_js']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("9e3fd19c-eec6-4659-8ad3-ba9967e4eb44"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("8a984818-6b5c-42ff-af2b-7499cce1fdd3"),
                            UrlXPath = "//div[contains(@class, 'big_photo')]//div[@class='big_photo__img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("7a590dd8-1f97-4724-b835-7ad47a4af6af"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("d3ff4b84-a0ff-4eb7-8ad4-9fbf56315c64"),
                            UrlXPath = "//div[@class='article__media']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("2e6e6d2a-517f-4273-bf82-aefdc4d74a9c"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1b6a8118-4743-4719-85ec-fa7549f5eaa3"),
                            UrlXPath = "//div[@class='inner_content']//div[@class='main_img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("1534c1db-64b4-446e-805d-42b738a798bc"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("fb5d1bb1-a8df-4edf-8e02-2d4d9e28c57f"),
                            UrlXPath = "//div[@class='b-material-incut-m-image']//@src"
                        },
                        new
                        {
                            Id = new Guid("62d57242-b8ad-4db0-9f7d-4d498fc620a6"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("4ec5e6b4-7ba8-40c9-816f-64ed86900e53"),
                            UrlXPath = "//article/figure/img/@src"
                        },
                        new
                        {
                            Id = new Guid("0c7d55a2-9e84-4a0d-ab9d-bbd750ecca5a"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("806fa257-eca5-419d-a26e-f1b7a3dcbcb3"),
                            UrlXPath = "//article//header/div[@class='article-head__photo']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("7a4628eb-2e32-4813-b061-1b395020bbec"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("f528a6df-4678-464b-9da9-97dd1b0b2fff"),
                            UrlXPath = "//article//header/div[contains(@class, 'styles_cover_media')]/img/@src"
                        },
                        new
                        {
                            Id = new Guid("0bf38a8f-24a6-471b-be65-206dd64c64f7"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("23d9436f-0d7b-40e3-957a-3a019c1dc109"),
                            UrlXPath = "//div[contains(@class, 'article-entry')]//div[contains(@class, 'entry-body')]//div[@class='source-wrapper']/img[@itemprop='image']/@src"
                        },
                        new
                        {
                            Id = new Guid("56f5bc5e-f5dc-4f33-a8f0-13cf44f8a699"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("13982eaf-47d9-4d24-b9db-eb15c34e9940"),
                            UrlXPath = "//a[@class='glightbox']/img[contains(@class, 'pub-cover')]/@src"
                        },
                        new
                        {
                            Id = new Guid("712d18a1-1b43-456b-95b9-92623aa0d24e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("84135793-ab32-4867-8bf1-8147b2b3c14c"),
                            UrlXPath = "//div[@class='b_article-media']//div[@class='mainarea-wrapper']/figure/img[@class='item-image-front']/@src"
                        },
                        new
                        {
                            Id = new Guid("e99d179c-87b7-45ed-be29-a22bc295b916"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("8363a541-546f-4a17-8ca3-3a6f0f4aa6c6"),
                            UrlXPath = "//div[contains(@class, 'full-article')]/div[contains(@class, 'gallery')]/picture/img/@src"
                        },
                        new
                        {
                            Id = new Guid("a813332c-13d6-49d2-a481-24bd6aef862f"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("77b72f9f-6883-4f7f-9a24-5aa83531a35a"),
                            UrlXPath = "//div[@itemprop='articleBody']//div[@itemprop='image']/picture/img[@itemprop='contentUrl']/@src"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("PublishedAtCultureInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_culture_info");

                    b.Property<string>("PublishedAtTimeZoneInfoId")
                        .HasColumnType("text")
                        .HasColumnName("published_at_time_zone_info_id");

                    b.Property<string>("PublishedAtXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_published_at_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_published_at_settings_parse_settings_id");

                    b.ToTable("news_parse_published_at_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1110f676-3cff-40b1-bce9-f9fbf8670d6a"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("c03dfd86-0f2e-4c0a-87d3-26d61263c773"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='article__info']//div[@class='article__info-date']/a/text()"
                        },
                        new
                        {
                            Id = new Guid("75283542-9d51-4618-9058-a4185dfd245c"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("5c9d7baf-aa66-4f1d-8558-95a3508b5aa2"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'article__date-autor-shortcode')]/div[contains(@class, 'article__date')]/time[@class='date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("a0948ee3-b602-46f1-909a-612b556846f8"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("e2be7c42-b23a-4849-b382-065f32cc9da6"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'NewsHeader')]//div[contains(@class, 'PublishedMark_publish')]//span[@ca-ts]/text()"
                        },
                        new
                        {
                            Id = new Guid("85e25ae9-ffe3-48b8-8544-23714b8e7eb6"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("774e9c7c-f642-465c-b93c-c2aacdf18b8f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='topic-page__header']//a[contains(@class, 'topic-header__time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("0301c739-b3ed-49dd-81e7-3622b886223e"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("84393779-d9b0-44f7-a563-d44269ff77b2"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'PageArticleContent_date')]/text()"
                        },
                        new
                        {
                            Id = new Guid("f200c997-33a8-47d0-9d70-d668f9cded0c"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("87b4be29-0d30-4a16-aa55-cfb56b544ec7"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='article_top']//div[@class='date']//time/text()"
                        },
                        new
                        {
                            Id = new Guid("d94b949b-9e2e-455c-9132-92beb6d15c2f"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("f80c5aa4-3026-4657-bb2b-90533ace23c5"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='article__header__info-block']/time[@class='article__header__date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("877ea725-9d8d-436a-ac76-2028d225a1eb"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("4fb1ad7e-ee34-45b8-b81c-251d94b8ad1f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//header[@class='news-item__header']//time/@content"
                        },
                        new
                        {
                            Id = new Guid("fd6fde86-91b2-4055-944e-df922792bccb"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("5ea05fa3-4d71-49e7-8467-febe303b82b9"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='doc_header__time']/time[@class='doc_header__publish_time']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("6c6b89e4-1d92-41ce-b1d1-844e867b6e18"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("8a984818-6b5c-42ff-af2b-7499cce1fdd3"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='article_page__left__top__left']//div[@class='article_page__left__top__time']//time/@datetime"
                        },
                        new
                        {
                            Id = new Guid("ccce8ef2-7ef6-4b9d-8b7e-7be93831931b"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("d3ff4b84-a0ff-4eb7-8ad4-9fbf56315c64"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='article__meta']/time/text()"
                        },
                        new
                        {
                            Id = new Guid("7a54675c-ba92-4713-9b22-3c6dc984ae6c"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("1b6a8118-4743-4719-85ec-fa7549f5eaa3"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='date_full']/text()"
                        },
                        new
                        {
                            Id = new Guid("40d198c1-49e5-441e-b861-bd353126a083"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("6b400ee2-13e2-4e71-b94f-a07d7a4123c8"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='b-text__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("e26d81af-8034-4b66-b890-14871a0aa85e"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("fb5d1bb1-a8df-4edf-8e02-2d4d9e28c57f"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//p[@class='b-material__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("4e628be8-6dfe-45f4-b356-3db02a1562d2"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("4ec5e6b4-7ba8-40c9-816f-64ed86900e53"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//article/div[@class='header']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("4e44521b-845d-4e25-a009-f325dc624ad1"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("806fa257-eca5-419d-a26e-f1b7a3dcbcb3"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtTimeZoneInfoId = "Russian Standard Time",
                            PublishedAtXPath = "//article//header//time[@class='article-head__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("c27cb571-1581-42c4-8fe8-89066e9cd97f"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("f528a6df-4678-464b-9da9-97dd1b0b2fff"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//article//header//div[contains(@class, 'styles_meta')]//div[contains(@class, 'styles_metaItem')]/text()"
                        },
                        new
                        {
                            Id = new Guid("640f4583-3762-4fc7-ae76-7d53013573a0"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("23d9436f-0d7b-40e3-957a-3a019c1dc109"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']/span[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("87d2b750-4f9c-4e8b-b28e-7d704171898e"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("d6374200-a1cd-46cd-9f88-14c86ab30e08"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='b-article__top-author']/p[@class='date']/text()"
                        },
                        new
                        {
                            Id = new Guid("239dba88-b9e9-4b43-aa6a-594e50bf792e"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("13982eaf-47d9-4d24-b9db-eb15c34e9940"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'publication-footer')]//div[contains(@class, 'pubdatetime')]//div[contains(@class, 'badge-time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("f728c9c4-46a3-406e-96ca-ff8bbefe2be8"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("84135793-ab32-4867-8bf1-8147b2b3c14c"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//article/div[@class='b_article-header']//time[@itemprop='datePublished']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("4a891695-2108-4830-bc76-9a5beee9b97f"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("e95e4af0-61c4-4706-b19f-56d0452651c3"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//article[@itemprop='articleBody']/meta[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("facc87ed-79de-4331-af38-a55e578354ce"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("8363a541-546f-4a17-8ca3-3a6f0f4aa6c6"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[contains(@class, 'full-article')]//time/text()"
                        },
                        new
                        {
                            Id = new Guid("32131a26-33ac-4792-997b-67dc86bd83b9"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("77b72f9f-6883-4f7f-9a24-5aa83531a35a"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtXPath = "//div[@class='publication-info']/time[@itemprop='datePublished']/@datetime"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettingsFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid>("NewsParsePublishedAtSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_parse_published_at_settings_id");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_published_at_settings_formats");

                    b.HasIndex("NewsParsePublishedAtSettingsId")
                        .HasDatabaseName("ix_news_parse_published_at_settings_formats_news_parse_publish");

                    b.ToTable("news_parse_published_at_settings_formats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7329c49d-f71c-4ed9-8547-29fae97d9456"),
                            Format = "HH:mm dd.MM.yyyy",
                            NewsParsePublishedAtSettingsId = new Guid("1110f676-3cff-40b1-bce9-f9fbf8670d6a")
                        },
                        new
                        {
                            Id = new Guid("b108c196-2298-450e-9493-10b1e7e71fdd"),
                            Format = "yyyy-MM-d HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("75283542-9d51-4618-9058-a4185dfd245c")
                        },
                        new
                        {
                            Id = new Guid("a0bbd6a1-2d74-4314-acd9-8df00f271bc3"),
                            Format = "dd MMMM yyyy, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("a0948ee3-b602-46f1-909a-612b556846f8")
                        },
                        new
                        {
                            Id = new Guid("32174a68-3272-4605-9e5d-549ca881ab5b"),
                            Format = "dd MMMM yyyy, HH:mm,",
                            NewsParsePublishedAtSettingsId = new Guid("a0948ee3-b602-46f1-909a-612b556846f8")
                        },
                        new
                        {
                            Id = new Guid("ff23b195-1d91-40cb-8e2a-210f26ea5448"),
                            Format = "dd MMMM, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("a0948ee3-b602-46f1-909a-612b556846f8")
                        },
                        new
                        {
                            Id = new Guid("cc8f7439-034b-414d-af92-4040888a8fa8"),
                            Format = "dd MMMM, HH:mm,",
                            NewsParsePublishedAtSettingsId = new Guid("a0948ee3-b602-46f1-909a-612b556846f8")
                        },
                        new
                        {
                            Id = new Guid("192e3c04-28a1-4338-a790-2ae76a86b530"),
                            Format = "HH:mm, dd MMMM yyyy",
                            NewsParsePublishedAtSettingsId = new Guid("85e25ae9-ffe3-48b8-8544-23714b8e7eb6")
                        },
                        new
                        {
                            Id = new Guid("cc42c4cf-7b69-4c97-bbdb-5c4864dd46ba"),
                            Format = "dd.MM.yyyy HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("0301c739-b3ed-49dd-81e7-3622b886223e")
                        },
                        new
                        {
                            Id = new Guid("ee0bd637-c250-445d-ad0e-4176ee364c23"),
                            Format = "dd.MM.yyyy HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("f200c997-33a8-47d0-9d70-d668f9cded0c")
                        },
                        new
                        {
                            Id = new Guid("fb242f5e-85dc-4ca0-88bd-3da0b9c31eb2"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("d94b949b-9e2e-455c-9132-92beb6d15c2f")
                        },
                        new
                        {
                            Id = new Guid("7a06108d-cba8-498e-be71-ec94a5552475"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("877ea725-9d8d-436a-ac76-2028d225a1eb")
                        },
                        new
                        {
                            Id = new Guid("4fbab705-2d48-47bb-b065-3b5121bc19f9"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("fd6fde86-91b2-4055-944e-df922792bccb")
                        },
                        new
                        {
                            Id = new Guid("7a3ac23e-a310-4c0f-9e47-47bf76f89ab3"),
                            Format = "yyyy-MM-ddTHH:mm:ssZ",
                            NewsParsePublishedAtSettingsId = new Guid("6c6b89e4-1d92-41ce-b1d1-844e867b6e18")
                        },
                        new
                        {
                            Id = new Guid("bf302518-54a6-49d6-ad0e-7ccba5d99bc4"),
                            Format = "dd MMMM yyyy HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("ccce8ef2-7ef6-4b9d-8b7e-7be93831931b")
                        },
                        new
                        {
                            Id = new Guid("05469217-b00b-4007-aa36-52bac41d0a69"),
                            Format = "dd MMMM yyyy, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("7a54675c-ba92-4713-9b22-3c6dc984ae6c")
                        },
                        new
                        {
                            Id = new Guid("e933a474-f9fb-4b5a-bd54-de8b8a6548b0"),
                            Format = "dd MMMM  HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("40d198c1-49e5-441e-b861-bd353126a083")
                        },
                        new
                        {
                            Id = new Guid("763b667c-05b7-4fe7-8ad2-c0a7160f6ff5"),
                            Format = "dd MMMM yyyy, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("e26d81af-8034-4b66-b890-14871a0aa85e")
                        },
                        new
                        {
                            Id = new Guid("424d1226-0511-4d53-966d-27f59a70d990"),
                            Format = "dd MMMM, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("e26d81af-8034-4b66-b890-14871a0aa85e")
                        },
                        new
                        {
                            Id = new Guid("066846f4-a1b2-4c65-851a-94004e96f768"),
                            Format = "dd MMMM yyyy, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("4e628be8-6dfe-45f4-b356-3db02a1562d2")
                        },
                        new
                        {
                            Id = new Guid("2379a18c-579b-4954-8240-9f8c3928db3d"),
                            Format = "dd MMMM yyyy, HH:mm МСК",
                            NewsParsePublishedAtSettingsId = new Guid("4e44521b-845d-4e25-a009-f325dc624ad1")
                        },
                        new
                        {
                            Id = new Guid("d8a7f19e-3f2a-4742-8bec-6841a3064c78"),
                            Format = "dd MMMM yyyy, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("c27cb571-1581-42c4-8fe8-89066e9cd97f")
                        },
                        new
                        {
                            Id = new Guid("13b5eaf6-08d7-4e69-8bed-ba5ebef9a776"),
                            Format = "dd MMMM, HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("c27cb571-1581-42c4-8fe8-89066e9cd97f")
                        },
                        new
                        {
                            Id = new Guid("7e539502-4512-4561-8675-85fa2ad4d27b"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("640f4583-3762-4fc7-ae76-7d53013573a0")
                        },
                        new
                        {
                            Id = new Guid("313dd5c9-4fe0-4316-b16c-346ae2c86b55"),
                            Format = "dd MMMM yyyy в HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("87d2b750-4f9c-4e8b-b28e-7d704171898e")
                        },
                        new
                        {
                            Id = new Guid("9f3a76d8-ee75-4dd2-a680-68726408188d"),
                            Format = "yyyy-MM-dd HH:mm:ss",
                            NewsParsePublishedAtSettingsId = new Guid("239dba88-b9e9-4b43-aa6a-594e50bf792e")
                        },
                        new
                        {
                            Id = new Guid("8e66fb91-295a-4215-9fa5-307af4505cef"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("f728c9c4-46a3-406e-96ca-ff8bbefe2be8")
                        },
                        new
                        {
                            Id = new Guid("82df79ce-2fb2-4143-abc9-4fa614abdddf"),
                            Format = "yyyy-MM-ddTHH:mm:ss",
                            NewsParsePublishedAtSettingsId = new Guid("4a891695-2108-4830-bc76-9a5beee9b97f")
                        },
                        new
                        {
                            Id = new Guid("8b608b3f-18ac-4fbe-b8c5-32f1f5d7b5fb"),
                            Format = "dd.MM.yyyy HH:mm",
                            NewsParsePublishedAtSettingsId = new Guid("facc87ed-79de-4331-af38-a55e578354ce")
                        },
                        new
                        {
                            Id = new Guid("93474fb1-b2f2-4396-adb4-7a137569d406"),
                            Format = "yyyy-MM-ddTHH:mm:sszzz",
                            NewsParsePublishedAtSettingsId = new Guid("32131a26-33ac-4792-997b-67dc86bd83b9")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_settings_source_id");

                    b.ToTable("news_parse_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c03dfd86-0f2e-4c0a-87d3-26d61263c773"),
                            DescriptionXPath = "//div[contains(@class, 'article__body')]",
                            SourceId = new Guid("5b025320-4dfb-4e1a-bd4c-cbab048a9887"),
                            TitleXPath = "//div[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("5c9d7baf-aa66-4f1d-8558-95a3508b5aa2"),
                            DescriptionXPath = "//div[contains(@class, 'article__text ')]",
                            SourceId = new Guid("e6df19fb-5945-4494-bdb0-7cb2b9efe746"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("e2be7c42-b23a-4849-b382-065f32cc9da6"),
                            DescriptionXPath = "//article",
                            SourceId = new Guid("2184c942-1eb2-411d-a976-683402ed8b54"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("774e9c7c-f642-465c-b93c-c2aacdf18b8f"),
                            DescriptionXPath = "//div[@class='topic-body__content']",
                            SourceId = new Guid("0fa8e5ea-4244-473f-9abd-8dcaf3707e8d"),
                            TitleXPath = "//h1[@class='topic-body__titles']/span[@class='topic-body__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("84393779-d9b0-44f7-a563-d44269ff77b2"),
                            DescriptionXPath = "//div[contains(@class, 'PageContentCommonStyling_text')]",
                            SourceId = new Guid("c8b92532-7530-4844-9b2e-131582c2192e"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("87b4be29-0d30-4a16-aa55-cfb56b544ec7"),
                            DescriptionXPath = "//div[@class='article_text']",
                            SourceId = new Guid("106e7393-cf77-4eaf-92b0-9c436a16a1ad"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("f80c5aa4-3026-4657-bb2b-90533ace23c5"),
                            DescriptionXPath = "//div[@class='article__text article__text_free']/*[not(contains(@class, 'article__text__overview'))]",
                            SourceId = new Guid("d07092e2-0010-42b3-b823-555909705bfe"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("4fb1ad7e-ee34-45b8-b81c-251d94b8ad1f"),
                            DescriptionXPath = "//div[contains(@class, 'news-item__content')]",
                            SourceId = new Guid("cb1580e3-5342-4eea-9bd2-da6114eceb69"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("5ea05fa3-4d71-49e7-8467-febe303b82b9"),
                            DescriptionXPath = "//div[@class='article_text_wrapper js-search-mark']/*[not(contains(@class, 'doc__text document_authors'))]",
                            SourceId = new Guid("7dabab2c-ce13-4271-b318-28d3cbd4c79a"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("8a984818-6b5c-42ff-af2b-7499cce1fdd3"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("4dfbcc91-5924-4405-8fec-7586e6bb06bf"),
                            TitleXPath = "//h1/span/text()"
                        },
                        new
                        {
                            Id = new Guid("d3ff4b84-a0ff-4eb7-8ad4-9fbf56315c64"),
                            DescriptionXPath = "//div[@class='article__content']/*[not(contains(@class, 'article__title')) and not(contains(@class, 'article__intro'))]",
                            SourceId = new Guid("487703fc-2e7e-474d-9899-014e085f461b"),
                            TitleXPath = "//h1[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("1b6a8118-4743-4719-85ec-fa7549f5eaa3"),
                            DescriptionXPath = "//div[@class='js-mediator-article']",
                            SourceId = new Guid("c6238797-90c0-40e3-a62c-38288829a529"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("6b400ee2-13e2-4e71-b94f-a07d7a4123c8"),
                            DescriptionXPath = "//div[@class='b-text__content']/div[contains(@class, 'b-text__block')]",
                            SourceId = new Guid("47b71370-cede-413a-b18f-5d79bf685b00"),
                            TitleXPath = "//h1[@class='b-text__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("fb5d1bb1-a8df-4edf-8e02-2d4d9e28c57f"),
                            DescriptionXPath = "//div[@class='b-material-body']/div/*[not(@class='b-material-incut-m-image')]",
                            SourceId = new Guid("855e70b2-8279-4709-a4a4-8e4292ca046f"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("4ec5e6b4-7ba8-40c9-816f-64ed86900e53"),
                            DescriptionXPath = "//article/div[@class='news_text']",
                            SourceId = new Guid("fc267691-ae48-4c5e-95be-1c9bc631d227"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("806fa257-eca5-419d-a26e-f1b7a3dcbcb3"),
                            DescriptionXPath = "//article/div[@class='article-content']/*[not(@class)]",
                            SourceId = new Guid("e75c511f-9fa9-46e7-ac28-66868f8e574b"),
                            TitleXPath = "//article/header/div[@class='article-head__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("f528a6df-4678-464b-9da9-97dd1b0b2fff"),
                            DescriptionXPath = "//div[contains(@class, 'styles_bodyWrapper')]/div[not(@class)]",
                            SourceId = new Guid("d667163b-f4a3-48c4-8c8a-ae8adb85bc49"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("23d9436f-0d7b-40e3-957a-3a019c1dc109"),
                            DescriptionXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()>1]",
                            SourceId = new Guid("9a98b275-8ce6-4343-98f6-88d8e4d7d1b8"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("d6374200-a1cd-46cd-9f88-14c86ab30e08"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("294e016c-f6a9-46b0-94f4-44b338ae53ae"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("13982eaf-47d9-4d24-b9db-eb15c34e9940"),
                            DescriptionXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']",
                            SourceId = new Guid("4f41e2c9-1c53-4e72-a40b-334b240659e6"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("84135793-ab32-4867-8bf1-8147b2b3c14c"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("c238a1cd-a273-4c33-bf64-c8e5fd49c89a"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("e95e4af0-61c4-4706-b19f-56d0452651c3"),
                            DescriptionXPath = "//article[@itemprop='articleBody']/*[not(name() = 'h1') and not(name() = 'aside') and not(name() = 'meta') and not(name() = 'link') and not(@itemprop)]",
                            SourceId = new Guid("c4c70a29-d889-4789-bf1f-73d7dbe3448b"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("8363a541-546f-4a17-8ca3-3a6f0f4aa6c6"),
                            DescriptionXPath = "//div[contains(@class, 'full-article')]/*[not(name()='h1') and not(name()='style') and not(name()='div')]",
                            SourceId = new Guid("01dd09e2-25ff-4639-8174-799d15a7eb4f"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("77b72f9f-6883-4f7f-9a24-5aa83531a35a"),
                            DescriptionXPath = "//div[@itemprop='articleBody']/*[not(name()='div')]",
                            SourceId = new Guid("34d0c0a0-e537-40bb-9511-257d5c2d6b68"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_sub_title_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_sub_title_settings_parse_settings_id");

                    b.ToTable("news_parse_sub_title_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5211f77-5906-40c4-b104-36dff477f32c"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("c03dfd86-0f2e-4c0a-87d3-26d61263c773"),
                            TitleXPath = "//h1[@class='article__second-title']/text()"
                        },
                        new
                        {
                            Id = new Guid("e8f7b058-106c-48b5-9525-9f149c35e1e2"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("5c9d7baf-aa66-4f1d-8558-95a3508b5aa2"),
                            TitleXPath = "//div[contains(@class, 'article__summary')]/text()"
                        },
                        new
                        {
                            Id = new Guid("7bac4c27-7aee-4a67-8b4e-bfc4bc6b7953"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("e2be7c42-b23a-4849-b382-065f32cc9da6"),
                            TitleXPath = "//h3/text()"
                        },
                        new
                        {
                            Id = new Guid("3cec968f-e38a-4696-b2b4-659ea5212947"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("774e9c7c-f642-465c-b93c-c2aacdf18b8f"),
                            TitleXPath = "//div[contains(@class, 'topic-body__title')]/text()"
                        },
                        new
                        {
                            Id = new Guid("ede7cf81-c35f-48ab-9f67-36780807b79e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("84393779-d9b0-44f7-a563-d44269ff77b2"),
                            TitleXPath = "//div[contains(@class, 'PageArticleContent_lead')]/text()"
                        },
                        new
                        {
                            Id = new Guid("d500e379-860b-47f9-86af-e11cedf814de"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("f80c5aa4-3026-4657-bb2b-90533ace23c5"),
                            TitleXPath = "//div[contains(@class, 'article__text')]/div[@class='article__text__overview']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("77035d2e-677a-4019-b1a6-faf2d802a781"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("5ea05fa3-4d71-49e7-8467-febe303b82b9"),
                            TitleXPath = "//header[@class='doc_header']/h2[contains(@class, 'doc_header__subheader')]/text()"
                        },
                        new
                        {
                            Id = new Guid("43a31de2-1054-4477-9649-5fb5f6ac7f21"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("d3ff4b84-a0ff-4eb7-8ad4-9fbf56315c64"),
                            TitleXPath = "//div[@class='article__intro']/p/text()"
                        },
                        new
                        {
                            Id = new Guid("85121d0c-b193-46f3-8242-2406de66007e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("4ec5e6b4-7ba8-40c9-816f-64ed86900e53"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("115081ae-41ef-4c7f-b515-18257f4c55c6"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("f528a6df-4678-464b-9da9-97dd1b0b2fff"),
                            TitleXPath = "//article//header//p[contains(@class, 'styles_subtitle')]/text()"
                        },
                        new
                        {
                            Id = new Guid("afd112bb-9b75-45e1-8cbc-f665f16e0b9e"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("23d9436f-0d7b-40e3-957a-3a019c1dc109"),
                            TitleXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()=1]/text()"
                        },
                        new
                        {
                            Id = new Guid("ede47109-eb34-47a9-aa4f-ff36f3ff3392"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d6374200-a1cd-46cd-9f88-14c86ab30e08"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("a431f970-f4a9-4095-87dd-69b0c79cfacc"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("13982eaf-47d9-4d24-b9db-eb15c34e9940"),
                            TitleXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']/text()"
                        },
                        new
                        {
                            Id = new Guid("622f55a9-7202-4b4f-bc2e-14e9d2d5d3db"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("84135793-ab32-4867-8bf1-8147b2b3c14c"),
                            TitleXPath = "//h2/text()"
                        },
                        new
                        {
                            Id = new Guid("554c8114-3fd6-46ff-9f5c-573e683411f8"),
                            IsRequired = true,
                            ParseSettingsId = new Guid("8363a541-546f-4a17-8ca3-3a6f0f4aa6c6"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_pictures");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_pictures_news_id");

                    b.ToTable("news_pictures", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NewsSiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_site_url");

                    b.Property<string>("NewsUrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_url_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_search_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_search_settings_source_id");

                    b.ToTable("news_search_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d60e5d48-fb65-4b49-9548-40f9c7f17925"),
                            NewsSiteUrl = "https://ria.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'cell-list__item-link')]/@href",
                            SourceId = new Guid("5b025320-4dfb-4e1a-bd4c-cbab048a9887")
                        },
                        new
                        {
                            Id = new Guid("5b1545af-7819-4999-9bb6-298ad10c8ffd"),
                            NewsSiteUrl = "https://russian.rt.com/",
                            NewsUrlXPath = "//a[contains(@class, 'link') and contains(@href, 'news/')]/@href",
                            SourceId = new Guid("e6df19fb-5945-4494-bdb0-7cb2b9efe746")
                        },
                        new
                        {
                            Id = new Guid("1b071b54-7880-44c1-bc5e-d403fb2133d4"),
                            NewsSiteUrl = "https://tass.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'tass_pkg_link-v5WdK') and contains(substring(@href, 2), '/')]/@href",
                            SourceId = new Guid("2184c942-1eb2-411d-a976-683402ed8b54")
                        },
                        new
                        {
                            Id = new Guid("3bf8beb0-b638-4ae1-8a1d-1b833a6d483b"),
                            NewsSiteUrl = "https://lenta.ru/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/')]/@href",
                            SourceId = new Guid("0fa8e5ea-4244-473f-9abd-8dcaf3707e8d")
                        },
                        new
                        {
                            Id = new Guid("4ae45096-2151-4a63-ac34-f7f5356291c6"),
                            NewsSiteUrl = "https://rg.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html')]/@href",
                            SourceId = new Guid("c8b92532-7530-4844-9b2e-131582c2192e")
                        },
                        new
                        {
                            Id = new Guid("08b4e01b-2410-4921-87e9-7f669a5ac066"),
                            NewsSiteUrl = "https://aif.ru/",
                            NewsUrlXPath = "//span[contains(@class, 'item_text__title')]/../@href",
                            SourceId = new Guid("106e7393-cf77-4eaf-92b0-9c436a16a1ad")
                        },
                        new
                        {
                            Id = new Guid("b081eadc-adaf-45c5-90b1-3ab61bafe616"),
                            NewsSiteUrl = "https://www.rbc.ru/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.rbc.ru/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("d07092e2-0010-42b3-b823-555909705bfe")
                        },
                        new
                        {
                            Id = new Guid("c647f9ef-4d1b-4379-8ebd-4e94888a3336"),
                            NewsSiteUrl = "https://www.sports.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '.html#comments'))]/@href",
                            SourceId = new Guid("cb1580e3-5342-4eea-9bd2-da6114eceb69")
                        },
                        new
                        {
                            Id = new Guid("6a341fd2-470a-4969-9c2b-bee12a02eb1b"),
                            NewsSiteUrl = "https://www.kommersant.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/doc/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("7dabab2c-ce13-4271-b318-28d3cbd4c79a")
                        },
                        new
                        {
                            Id = new Guid("aa0a0a3b-c73b-4cbc-b73d-5408d060e8b1"),
                            NewsSiteUrl = "https://iz.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '?main_click')]/@href",
                            SourceId = new Guid("4dfbcc91-5924-4405-8fec-7586e6bb06bf")
                        },
                        new
                        {
                            Id = new Guid("467ba11c-f695-4e41-9dc0-58e22b7d410b"),
                            NewsSiteUrl = "https://tsargrad.tv/",
                            NewsUrlXPath = "//a[contains(@class, 'news-item__link')]/@href",
                            SourceId = new Guid("487703fc-2e7e-474d-9899-014e085f461b")
                        },
                        new
                        {
                            Id = new Guid("e1c03a0d-6ccb-41c9-8957-98a7472ebf48"),
                            NewsSiteUrl = "https://www.belta.by/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.belta.by/') and contains(@href, '/view/')]/@href",
                            SourceId = new Guid("c6238797-90c0-40e3-a62c-38288829a529")
                        },
                        new
                        {
                            Id = new Guid("41104bd1-d6b8-4f3f-837c-3354e1b56f67"),
                            NewsSiteUrl = "https://svpressa.ru/all/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(contains(@href, '?')) and not(starts-with(@href, '/all/news/'))]/@href",
                            SourceId = new Guid("47b71370-cede-413a-b18f-5d79bf685b00")
                        },
                        new
                        {
                            Id = new Guid("942da78e-c48a-4233-8391-a587ec271e23"),
                            NewsSiteUrl = "https://www.m24.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("855e70b2-8279-4709-a4a4-8e4292ca046f")
                        },
                        new
                        {
                            Id = new Guid("035bc0b6-dc5b-4eaf-8210-cfd501a023a1"),
                            NewsSiteUrl = "https://vz.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '#comments')) and not(contains(@href, '?')) and not(contains(@href, '/about/'))]/@href",
                            SourceId = new Guid("fc267691-ae48-4c5e-95be-1c9bc631d227")
                        },
                        new
                        {
                            Id = new Guid("967d54a8-1daf-4415-acd5-32e343f54bc6"),
                            NewsSiteUrl = "https://www.championat.com/news/1.html?utm_source=button&utm_medium=news",
                            NewsUrlXPath = "//a[contains(@href, 'news-') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("e75c511f-9fa9-46e7-ac28-66868f8e574b")
                        },
                        new
                        {
                            Id = new Guid("fb5db5e3-8012-4151-93cb-e9618cc93563"),
                            NewsSiteUrl = "https://life.ru/s/novosti",
                            NewsUrlXPath = "//a[contains(@href, '/p/')]/@href",
                            SourceId = new Guid("d667163b-f4a3-48c4-8c8a-ae8adb85bc49")
                        },
                        new
                        {
                            Id = new Guid("a62728fa-16c3-4fe1-b672-270215ff18c3"),
                            NewsSiteUrl = "https://3dnews.ru/news/",
                            NewsUrlXPath = "//div[@class='news-feed-all']//a[@class='entry-header']/h1/../@href",
                            SourceId = new Guid("9a98b275-8ce6-4343-98f6-88d8e4d7d1b8")
                        },
                        new
                        {
                            Id = new Guid("317de6d6-8693-49ff-b21e-5cffb88c0280"),
                            NewsSiteUrl = "https://www.ixbt.com/news/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("294e016c-f6a9-46b0-94f4-44b338ae53ae")
                        },
                        new
                        {
                            Id = new Guid("c77a7d25-5c7b-4e51-8899-97ec6fa80bf9"),
                            NewsSiteUrl = "https://ixbt.games/news/",
                            NewsUrlXPath = "//a[@class='card-link']/@href",
                            SourceId = new Guid("4f41e2c9-1c53-4e72-a40b-334b240659e6")
                        },
                        new
                        {
                            Id = new Guid("9fce02ac-c29b-4202-857c-468669a01021"),
                            NewsSiteUrl = "https://www.gazeta.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and contains(@href, '.shtml') and not(contains(@href, '?'))]/@href",
                            SourceId = new Guid("c238a1cd-a273-4c33-bf64-c8e5fd49c89a")
                        },
                        new
                        {
                            Id = new Guid("e7454a43-e0ef-4c47-ae35-9b91392ecf45"),
                            NewsSiteUrl = "https://www.interfax.ru/",
                            NewsUrlXPath = "//div[@class='timeline']//a[@tabindex=5]/@href",
                            SourceId = new Guid("c4c70a29-d889-4789-bf1f-73d7dbe3448b")
                        },
                        new
                        {
                            Id = new Guid("4b1b72fa-2c19-47f2-8a6f-8e82c2059966"),
                            NewsSiteUrl = "https://www.pravda.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(@href='https://www.pravda.ru/news/')]/@href",
                            SourceId = new Guid("01dd09e2-25ff-4639-8174-799d15a7eb4f")
                        },
                        new
                        {
                            Id = new Guid("e7d44937-8065-4e09-9636-2b694cd638d6"),
                            NewsSiteUrl = "https://ura.news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("34d0c0a0-e537-40bb-9511-257d5c2d6b68")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sources");

                    b.HasIndex("Title", "SiteUrl", "IsEnabled")
                        .HasDatabaseName("ix_news_sources_title_site_url_is_enabled");

                    b.ToTable("news_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b025320-4dfb-4e1a-bd4c-cbab048a9887"),
                            IsEnabled = true,
                            SiteUrl = "https://ria.ru/",
                            Title = "РИА Новости"
                        },
                        new
                        {
                            Id = new Guid("e6df19fb-5945-4494-bdb0-7cb2b9efe746"),
                            IsEnabled = true,
                            SiteUrl = "https://russian.rt.com/",
                            Title = "RT на русском"
                        },
                        new
                        {
                            Id = new Guid("2184c942-1eb2-411d-a976-683402ed8b54"),
                            IsEnabled = true,
                            SiteUrl = "https://tass.ru/",
                            Title = "ТАСС"
                        },
                        new
                        {
                            Id = new Guid("0fa8e5ea-4244-473f-9abd-8dcaf3707e8d"),
                            IsEnabled = true,
                            SiteUrl = "https://lenta.ru/",
                            Title = "Лента.Ру"
                        },
                        new
                        {
                            Id = new Guid("c8b92532-7530-4844-9b2e-131582c2192e"),
                            IsEnabled = true,
                            SiteUrl = "https://rg.ru/",
                            Title = "Российская газета"
                        },
                        new
                        {
                            Id = new Guid("106e7393-cf77-4eaf-92b0-9c436a16a1ad"),
                            IsEnabled = true,
                            SiteUrl = "https://aif.ru/",
                            Title = "Аргументы и факты"
                        },
                        new
                        {
                            Id = new Guid("d07092e2-0010-42b3-b823-555909705bfe"),
                            IsEnabled = true,
                            SiteUrl = "https://www.rbc.ru/",
                            Title = "РБК"
                        },
                        new
                        {
                            Id = new Guid("cb1580e3-5342-4eea-9bd2-da6114eceb69"),
                            IsEnabled = true,
                            SiteUrl = "https://www.sports.ru/",
                            Title = "Storts.ru"
                        },
                        new
                        {
                            Id = new Guid("7dabab2c-ce13-4271-b318-28d3cbd4c79a"),
                            IsEnabled = true,
                            SiteUrl = "https://www.kommersant.ru/",
                            Title = "Коммерсантъ"
                        },
                        new
                        {
                            Id = new Guid("4dfbcc91-5924-4405-8fec-7586e6bb06bf"),
                            IsEnabled = true,
                            SiteUrl = "https://iz.ru/",
                            Title = "Известия"
                        },
                        new
                        {
                            Id = new Guid("487703fc-2e7e-474d-9899-014e085f461b"),
                            IsEnabled = false,
                            SiteUrl = "https://tsargrad.tv/",
                            Title = "Царьград"
                        },
                        new
                        {
                            Id = new Guid("c6238797-90c0-40e3-a62c-38288829a529"),
                            IsEnabled = true,
                            SiteUrl = "https://www.belta.by/",
                            Title = "БелТА"
                        },
                        new
                        {
                            Id = new Guid("47b71370-cede-413a-b18f-5d79bf685b00"),
                            IsEnabled = true,
                            SiteUrl = "https://svpressa.ru/",
                            Title = "СвободнаяПресса"
                        },
                        new
                        {
                            Id = new Guid("855e70b2-8279-4709-a4a4-8e4292ca046f"),
                            IsEnabled = true,
                            SiteUrl = "https://www.m24.ru/",
                            Title = "Москва 24"
                        },
                        new
                        {
                            Id = new Guid("fc267691-ae48-4c5e-95be-1c9bc631d227"),
                            IsEnabled = true,
                            SiteUrl = "https://vz.ru/",
                            Title = "ВЗГЛЯД.РУ"
                        },
                        new
                        {
                            Id = new Guid("e75c511f-9fa9-46e7-ac28-66868f8e574b"),
                            IsEnabled = true,
                            SiteUrl = "https://www.championat.com/",
                            Title = "Чемпионат.com"
                        },
                        new
                        {
                            Id = new Guid("d667163b-f4a3-48c4-8c8a-ae8adb85bc49"),
                            IsEnabled = true,
                            SiteUrl = "https://life.ru/",
                            Title = "Life"
                        },
                        new
                        {
                            Id = new Guid("9a98b275-8ce6-4343-98f6-88d8e4d7d1b8"),
                            IsEnabled = true,
                            SiteUrl = "https://3dnews.ru/",
                            Title = "3Dnews.ru"
                        },
                        new
                        {
                            Id = new Guid("294e016c-f6a9-46b0-94f4-44b338ae53ae"),
                            IsEnabled = true,
                            SiteUrl = "https://www.ixbt.com/",
                            Title = "iXBT.com"
                        },
                        new
                        {
                            Id = new Guid("4f41e2c9-1c53-4e72-a40b-334b240659e6"),
                            IsEnabled = false,
                            SiteUrl = "https://ixbt.games/",
                            Title = "iXBT.games"
                        },
                        new
                        {
                            Id = new Guid("c238a1cd-a273-4c33-bf64-c8e5fd49c89a"),
                            IsEnabled = true,
                            SiteUrl = "https://www.gazeta.ru/",
                            Title = "Газета.Ru"
                        },
                        new
                        {
                            Id = new Guid("c4c70a29-d889-4789-bf1f-73d7dbe3448b"),
                            IsEnabled = true,
                            SiteUrl = "https://www.interfax.ru/",
                            Title = "Интерфакс"
                        },
                        new
                        {
                            Id = new Guid("01dd09e2-25ff-4639-8174-799d15a7eb4f"),
                            IsEnabled = true,
                            SiteUrl = "https://www.pravda.ru/",
                            Title = "Правда.ру"
                        },
                        new
                        {
                            Id = new Guid("34d0c0a0-e537-40bb-9511-257d5c2d6b68"),
                            IsEnabled = true,
                            SiteUrl = "https://ura.news/",
                            Title = "Ura.ru"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_source_logos");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_source_logos_source_id");

                    b.ToTable("news_source_logos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df57af4a-ba39-40b8-b262-b696ebbe169a"),
                            SourceId = new Guid("4f41e2c9-1c53-4e72-a40b-334b240659e6"),
                            Url = "https://sun13-2.userapi.com/s/v1/ig2/_ID-2w6Llad8ig5_987dKAfh1pyLdj7HfLHqGx9HxyDjoEDN7wxR0ZWJm5ja1Ey6UuQXaEYEBW1Zd51cpRrjSGfS.jpg?size=100x100&quality=96&crop=22,22,626,626&ava=1"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sub_titles");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_sub_titles_news_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_news_sub_titles_title");

                    b.ToTable("news_sub_titles", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", "Editor")
                        .WithMany("News")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_news_editors_editor_id");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Description")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_descriptions_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithMany("Editors")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_editors_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseEditorSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_editor_settings_news_parse_settings_parse_settin");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePictureSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_picture_settings_news_parse_settings_parse_setti");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePublishedAtSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_published_at_settings_news_parse_settings_parse_");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettingsFormat", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", "Settings")
                        .WithMany("Formats")
                        .HasForeignKey("NewsParsePublishedAtSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_published_at_settings_formats_news_parse_publish");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("ParseSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseSubTitleSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_sub_title_settings_news_parse_settings_parse_set");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Picture")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_pictures_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("SearchSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_search_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("Logo")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_source_logos_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("SubTitle")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_sub_titles_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Picture");

                    b.Navigation("SubTitle");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.Navigation("Formats");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Navigation("ParseEditorSettings");

                    b.Navigation("ParsePictureSettings");

                    b.Navigation("ParsePublishedAtSettings");

                    b.Navigation("ParseSubTitleSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Navigation("Editors");

                    b.Navigation("Logo");

                    b.Navigation("ParseSettings");

                    b.Navigation("SearchSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
