// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAggregator.News.Databases.EntityFramework.News;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsAggregator.News.Databases.EntityFramework.News.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_news_editor_id");

                    b.HasIndex("Url", "Title")
                        .HasDatabaseName("ix_news_url_title");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_news_descriptions");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_descriptions_news_id");

                    b.ToTable("news_descriptions", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_editors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_news_editors_name");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_news_editors_source_id");

                    b.ToTable("news_editors", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("NameXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_x_path");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_editor_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_editor_settings_parse_settings_id");

                    b.ToTable("news_parse_editor_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("557f1ea5-b05b-4fb9-a891-6f03f754dac5"),
                            IsRequired = false,
                            NameXPath = "//div[@class='topic-authors']/a[@class='topic-authors__author']/text()",
                            ParseSettingsId = new Guid("13c63e40-ce79-41e4-9b46-dcafe1cce434")
                        },
                        new
                        {
                            Id = new Guid("ec219c28-247b-471e-92f1-cc23ffb9fb21"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'PageArticleContent_authors')]//a[contains(@class, 'LinksOfAuthor_item')]/text()",
                            ParseSettingsId = new Guid("3933a019-c0e5-4e34-a33e-9373cee6758a")
                        },
                        new
                        {
                            Id = new Guid("dbb5d05d-ca10-41c6-8362-b376e6be59dc"),
                            IsRequired = false,
                            NameXPath = "//div[@class='article_top']//div[@class='authors']//div[@class='autor']//span/text()",
                            ParseSettingsId = new Guid("d5f3849b-40cb-4ceb-bbcd-8903b97d8e93")
                        },
                        new
                        {
                            Id = new Guid("6034acae-fee9-4001-ad57-25dfcdf2913b"),
                            IsRequired = false,
                            NameXPath = "//div[@class='article__authors']//span[@class='article__authors__author']/span[@class='article__authors__author__name']/text()",
                            ParseSettingsId = new Guid("048afc27-d220-4129-918b-d5a1e9989e21")
                        },
                        new
                        {
                            Id = new Guid("9960f528-e582-44ec-8784-91e2aaad7f0b"),
                            IsRequired = false,
                            NameXPath = "//footer[@class='news-item__footer']/div[@class='news-item__footer-after-news']/p[position()=1]//span/text()",
                            ParseSettingsId = new Guid("c015cb02-92f7-40ca-846c-afe21950a399")
                        },
                        new
                        {
                            Id = new Guid("8a305001-16ef-4c01-9fb7-87a8d7e5181b"),
                            IsRequired = false,
                            NameXPath = "//p[@class='doc__text document_authors']/text()",
                            ParseSettingsId = new Guid("b2628384-b53c-4e6d-a380-f06b7fa40fa1")
                        },
                        new
                        {
                            Id = new Guid("f8452007-e414-4e32-9a3a-e7fe448dd9e9"),
                            IsRequired = false,
                            NameXPath = "//a[@class='article__author']/text()",
                            ParseSettingsId = new Guid("1199fb6e-d599-4e79-8fcf-c327e287c527")
                        },
                        new
                        {
                            Id = new Guid("cf51679e-4658-4c80-89c5-17fc3de7cdb4"),
                            IsRequired = false,
                            NameXPath = "//article//header//div[@class='article-head__author-name']/a[@rel='author']/span/text()",
                            ParseSettingsId = new Guid("121162a8-6a7c-4e61-9e54-ef037e135a8d")
                        },
                        new
                        {
                            Id = new Guid("4e76fd02-c6cb-4cfd-8062-8666eb1498d7"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'styles_bodyWrapper')]//div[contains(@class, 'styles_authorsLinks')]/a/text()",
                            ParseSettingsId = new Guid("f40d9536-44e5-45cf-95a0-ed05a887ee19")
                        },
                        new
                        {
                            Id = new Guid("a4487be2-332a-4b31-8b3a-1cbb4649a8f3"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']//a[@itemprop='author']//span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("d8bd2f21-e873-442f-bec7-c9a7930d2db1")
                        },
                        new
                        {
                            Id = new Guid("18c9baa2-ead4-456d-93c1-5980861fc762"),
                            IsRequired = false,
                            NameXPath = "//span[@itemprop='author']/span[@itemprop='name']/@content",
                            ParseSettingsId = new Guid("7ad5cd9a-4de7-42d1-9d50-a705754196f5")
                        },
                        new
                        {
                            Id = new Guid("e80ddfbe-f4f5-4904-8c72-b5292b433361"),
                            IsRequired = false,
                            NameXPath = "//div[@class='container-fluid publication-footer']//a[contains(@class, 'text-secondary')]/@title",
                            ParseSettingsId = new Guid("beeb9b0d-f3c3-4051-9a83-ea8758fcf977")
                        },
                        new
                        {
                            Id = new Guid("0a643c92-9fc7-4271-ba76-628be8896cc6"),
                            IsRequired = false,
                            NameXPath = "//div[@class='author']/span[@itemprop='author']/span[@itemprop='name']/a/text()",
                            ParseSettingsId = new Guid("a69e9126-aa28-4fe5-a7bd-be9d6117938e")
                        },
                        new
                        {
                            Id = new Guid("cd0f71c9-5001-4ada-9c93-21ad4ff152b2"),
                            IsRequired = false,
                            NameXPath = "//div[contains(@class, 'full-article')]/div[@class='authors-block']//span[text()='Автор']/../a/text()",
                            ParseSettingsId = new Guid("38481a31-8043-454c-b720-49c4efb3aeef")
                        },
                        new
                        {
                            Id = new Guid("0447ce9e-0d45-4d03-89ac-8581145663df"),
                            IsRequired = false,
                            NameXPath = "//div[@itemprop='author']/span[@itemprop='name']/text()",
                            ParseSettingsId = new Guid("bd5e633f-793a-44d7-bee4-6104660d8326")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("UrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_picture_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_picture_settings_parse_settings_id");

                    b.ToTable("news_parse_picture_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8381dc9f-ef9b-46a3-a458-4ac1f21c5545"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("62b37a37-4fd7-4dbe-8b53-25e936db2e02"),
                            UrlXPath = "//div[@class='photoview__open']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("bf4194e1-c62d-4586-a043-d26851a2db50"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("2428fc94-f50e-473d-b266-4d797fac1316"),
                            UrlXPath = "//div[contains(@class, 'HeaderMedia_image')]//img[contains(@class, 'Image_image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("48c77a34-1d10-4b2a-9a4c-d8c7a9787b93"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("13c63e40-ce79-41e4-9b46-dcafe1cce434"),
                            UrlXPath = "//div[contains(@class, 'topic-body__title-image')]//img[contains(@class, 'picture__image')]/@src"
                        },
                        new
                        {
                            Id = new Guid("1bc1c0a0-691b-42dc-86b1-0ff1406119e8"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d5f3849b-40cb-4ceb-bbcd-8903b97d8e93"),
                            UrlXPath = "//div[@class='img_box']/a[@class='zoom_js']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("663c37be-3057-4e83-8173-fa4ea99dc132"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("01902fcd-cd21-4d96-bf1f-5dfc7812381e"),
                            UrlXPath = "//div[contains(@class, 'big_photo')]//div[@class='big_photo__img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("469d60fa-2a8f-433a-98a3-0f10160eb375"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1199fb6e-d599-4e79-8fcf-c327e287c527"),
                            UrlXPath = "//div[@class='article__media']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("104c6919-3fbb-4c8f-ad3b-523f37972ce3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("583e3321-929d-4526-ba27-734c0fd62f23"),
                            UrlXPath = "//div[@class='inner_content']//div[@class='main_img']//img/@src"
                        },
                        new
                        {
                            Id = new Guid("fc58cb55-6475-47c8-a230-0e1103e564c6"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c38454ee-bc5a-4045-9924-7098e80f1976"),
                            UrlXPath = "//div[@class='b-material-incut-m-image']//@src"
                        },
                        new
                        {
                            Id = new Guid("d0948c9c-7751-4db2-862d-450837584825"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1a7ff9f2-4a8f-4138-857c-16e9873187db"),
                            UrlXPath = "//article/figure/img/@src"
                        },
                        new
                        {
                            Id = new Guid("993f5306-e7a0-4747-a1dd-cee580b2b110"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("121162a8-6a7c-4e61-9e54-ef037e135a8d"),
                            UrlXPath = "//article//header/div[@class='article-head__photo']/img/@src"
                        },
                        new
                        {
                            Id = new Guid("aecefde1-848d-450f-96dc-32dcd4d678d3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("f40d9536-44e5-45cf-95a0-ed05a887ee19"),
                            UrlXPath = "//article//header/div[contains(@class, 'styles_cover_media')]/img/@src"
                        },
                        new
                        {
                            Id = new Guid("1e79ee61-dc5c-4eeb-9632-775bb33f54cc"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d8bd2f21-e873-442f-bec7-c9a7930d2db1"),
                            UrlXPath = "//div[contains(@class, 'article-entry')]//div[contains(@class, 'entry-body')]//div[@class='source-wrapper']/img[@itemprop='image']/@src"
                        },
                        new
                        {
                            Id = new Guid("970c9a11-0351-4cec-a491-dbd27cd4bd4f"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("beeb9b0d-f3c3-4051-9a83-ea8758fcf977"),
                            UrlXPath = "//a[@class='glightbox']/img[contains(@class, 'pub-cover')]/@src"
                        },
                        new
                        {
                            Id = new Guid("76002a71-4908-4653-a2ce-ad37107a5097"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("a69e9126-aa28-4fe5-a7bd-be9d6117938e"),
                            UrlXPath = "//div[@class='b_article-media']//div[@class='mainarea-wrapper']/figure/img[@class='item-image-front']/@src"
                        },
                        new
                        {
                            Id = new Guid("99b4102a-cce9-46c2-b7ed-7fda19a730ca"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("38481a31-8043-454c-b720-49c4efb3aeef"),
                            UrlXPath = "//div[contains(@class, 'full-article')]/div[contains(@class, 'gallery')]/picture/img/@src"
                        },
                        new
                        {
                            Id = new Guid("cc4bf93a-cd61-4ae7-98b9-e00501a4ffcb"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("bd5e633f-793a-44d7-bee4-6104660d8326"),
                            UrlXPath = "//div[@itemprop='articleBody']//div[@itemprop='image']/picture/img[@itemprop='contentUrl']/@src"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("PublishedAtCultureInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_culture_info");

                    b.Property<string>("PublishedAtFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_format");

                    b.Property<string>("PublishedAtXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("published_at_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_published_at_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_published_at_settings_parse_settings_id");

                    b.ToTable("news_parse_published_at_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa3c2586-f5b6-4605-8e67-d13dacedae5d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("62b37a37-4fd7-4dbe-8b53-25e936db2e02"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm dd.MM.yyyy",
                            PublishedAtXPath = "//div[@class='article__info']//div[@class='article__info-date']/a/text()"
                        },
                        new
                        {
                            Id = new Guid("fbf1aced-5867-4e8a-a7f3-bf199b5e5511"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("de1c0851-8bd0-42f4-adcb-c57c9f397cdb"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-d HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'article__date-autor-shortcode')]/div[contains(@class, 'article__date')]/time[@class='date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("4dc98414-5c74-49f0-bb3a-0d075ff8e47d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("13c63e40-ce79-41e4-9b46-dcafe1cce434"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm, d M yyyy",
                            PublishedAtXPath = "//div[@class='topic-page__header']//a[contains(@class, 'topic-header__time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("447ed99c-f28a-47d3-b100-29ef7f7a92f5"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("3933a019-c0e5-4e34-a33e-9373cee6758a"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'PageArticleContent_date')]/text()"
                        },
                        new
                        {
                            Id = new Guid("558dbd47-cf6f-4815-86b9-0c14453e2990"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d5f3849b-40cb-4ceb-bbcd-8903b97d8e93"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[@class='article_top']//div[@class='date']//time/text()"
                        },
                        new
                        {
                            Id = new Guid("c2b6a038-9b64-45ba-9d54-9eca2c38086e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("048afc27-d220-4129-918b-d5a1e9989e21"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='article__header__info-block']/time[@class='article__header__date']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("c4476e2e-f94d-473c-b8e2-1ce17202af99"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c015cb02-92f7-40ca-846c-afe21950a399"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//header[@class='news-item__header']//time/@content"
                        },
                        new
                        {
                            Id = new Guid("eaaf0d83-eb7b-49f6-a1c1-b79e76aaf696"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b2628384-b53c-4e6d-a380-f06b7fa40fa1"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='doc_header__time']/time[@class='doc_header__publish_time']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("477b48ff-eade-4fe2-bce2-75bd42a55ee5"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("01902fcd-cd21-4d96-bf1f-5dfc7812381e"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:ssZ",
                            PublishedAtXPath = "//div[@class='article_page__left__top__left']//div[@class='article_page__left__top__time']//time/@datetime"
                        },
                        new
                        {
                            Id = new Guid("4d01ba31-2bcf-4b8c-8e9c-af523b84be32"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("583e3321-929d-4526-ba27-734c0fd62f23"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd M yyyy, HH:mm",
                            PublishedAtXPath = "//div[@class='date_full']/text()"
                        },
                        new
                        {
                            Id = new Guid("43a31e4a-08a9-40f9-9ad2-a11e1d303fd7"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("c38454ee-bc5a-4045-9924-7098e80f1976"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "HH:mm",
                            PublishedAtXPath = "//p[@class='b-material__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("0ace0c78-e1fa-4c04-a8a7-62661ff70a1d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1a7ff9f2-4a8f-4138-857c-16e9873187db"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd M yyyy, HH:mm",
                            PublishedAtXPath = "//article/div[@class='header']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("8129b5c7-8dcb-4dbd-87c0-eb8d780319a6"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("121162a8-6a7c-4e61-9e54-ef037e135a8d"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd M yyyy, HH:mm",
                            PublishedAtXPath = "//article//header//time[@class='article-head__date']/text()"
                        },
                        new
                        {
                            Id = new Guid("7727460b-c679-41e6-a052-1b99e3c2e109"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d8bd2f21-e873-442f-bec7-c9a7930d2db1"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[contains(@class, 'article-entry')]//div[@class='entry-info']/span[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("3ac8274e-b682-4d31-9f9e-2d22789119b8"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7ad5cd9a-4de7-42d1-9d50-a705754196f5"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd M yyyy в HH:mm",
                            PublishedAtXPath = "//div[@class='b-article__top-author']/p[@class='date']/text()"
                        },
                        new
                        {
                            Id = new Guid("29a41b0b-2fae-4a80-bbcf-752254bc2df2"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("beeb9b0d-f3c3-4051-9a83-ea8758fcf977"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-dd HH:mm:ss",
                            PublishedAtXPath = "//div[contains(@class, 'publication-footer')]//div[contains(@class, 'pubdatetime')]//div[contains(@class, 'badge-time')]/text()"
                        },
                        new
                        {
                            Id = new Guid("e0f78653-0a00-4acc-bb1f-58af7ee64d74"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("a69e9126-aa28-4fe5-a7bd-be9d6117938e"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//article/div[@class='b_article-header']//time[@itemprop='datePublished']/@datetime"
                        },
                        new
                        {
                            Id = new Guid("8453b75e-e1af-4c46-89a4-e870eca3bdcf"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b59d6368-6740-4aed-af58-ae2f5383f88e"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:ss",
                            PublishedAtXPath = "//article[@itemprop='articleBody']/meta[@itemprop='datePublished']/@content"
                        },
                        new
                        {
                            Id = new Guid("c7702441-b477-4297-9121-a3bf4b0f4041"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("38481a31-8043-454c-b720-49c4efb3aeef"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "dd.MM.yyyy HH:mm",
                            PublishedAtXPath = "//div[contains(@class, 'full-article')]//time/text()"
                        },
                        new
                        {
                            Id = new Guid("b814183d-5ece-4ce1-bf14-5e8b489a90eb"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("bd5e633f-793a-44d7-bee4-6104660d8326"),
                            PublishedAtCultureInfo = "ru-RU",
                            PublishedAtFormat = "yyyy-MM-ddTHH:mm:sszzz",
                            PublishedAtXPath = "//div[@class='publication-info']/time[@itemprop='datePublished']/@datetime"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_settings_source_id");

                    b.ToTable("news_parse_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("62b37a37-4fd7-4dbe-8b53-25e936db2e02"),
                            DescriptionXPath = "//div[contains(@class, 'article__body')]",
                            SourceId = new Guid("16425339-cf3e-4837-8613-c6d08cd42ea6"),
                            TitleXPath = "//div[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("de1c0851-8bd0-42f4-adcb-c57c9f397cdb"),
                            DescriptionXPath = "//div[contains(@class, 'article__text ')]",
                            SourceId = new Guid("09ffcd85-9795-4f77-8e55-68d40e34d87a"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("2428fc94-f50e-473d-b266-4d797fac1316"),
                            DescriptionXPath = "//article",
                            SourceId = new Guid("d74c7a85-d4a8-44bc-8c5f-bc5f71b60c75"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("13c63e40-ce79-41e4-9b46-dcafe1cce434"),
                            DescriptionXPath = "//div[@class='topic-body__content']",
                            SourceId = new Guid("f882277e-6851-4590-bcb9-424a7751c1af"),
                            TitleXPath = "//h1[@class='topic-body__titles']/span[@class='topic-body__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("3933a019-c0e5-4e34-a33e-9373cee6758a"),
                            DescriptionXPath = "//div[contains(@class, 'PageContentCommonStyling_text')]",
                            SourceId = new Guid("0e267466-ad14-4f7b-8b00-d278dc128fd7"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("d5f3849b-40cb-4ceb-bbcd-8903b97d8e93"),
                            DescriptionXPath = "//div[@class='article_text']",
                            SourceId = new Guid("2eb0a1ad-38ed-4aa2-8a73-4d80f156f815"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("048afc27-d220-4129-918b-d5a1e9989e21"),
                            DescriptionXPath = "//div[@class='article__text article__text_free']/*[not(contains(@class, 'article__text__overview'))]",
                            SourceId = new Guid("98fac15c-fc17-4012-a827-cf12e4fc72fc"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("c015cb02-92f7-40ca-846c-afe21950a399"),
                            DescriptionXPath = "//div[contains(@class, 'news-item__content')]",
                            SourceId = new Guid("a6e56b29-cb95-428a-b676-1607db592bce"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("b2628384-b53c-4e6d-a380-f06b7fa40fa1"),
                            DescriptionXPath = "//div[@class='article_text_wrapper js-search-mark']/*[not(contains(@class, 'doc__text document_authors'))]",
                            SourceId = new Guid("f6f82166-9205-4978-b093-c39b66fab4f3"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("01902fcd-cd21-4d96-bf1f-5dfc7812381e"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("ab6e74cd-405f-489f-8672-c8923c8fa9ec"),
                            TitleXPath = "//h1/span/text()"
                        },
                        new
                        {
                            Id = new Guid("1199fb6e-d599-4e79-8fcf-c327e287c527"),
                            DescriptionXPath = "//div[@class='article__content']/*[not(contains(@class, 'article__title')) and not(contains(@class, 'article__intro'))]",
                            SourceId = new Guid("d8c2325c-a066-4d5f-a080-bc4a8086b9e4"),
                            TitleXPath = "//h1[@class='article__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("583e3321-929d-4526-ba27-734c0fd62f23"),
                            DescriptionXPath = "//div[@class='js-mediator-article']",
                            SourceId = new Guid("a05bc4f7-d5bc-490b-8593-0171551c9958"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("4edefbc4-7e11-4710-9002-bd557198d69d"),
                            DescriptionXPath = "//div[@class='b-text__content']/div[contains(@class, 'b-text__block')]",
                            SourceId = new Guid("f3759f29-9364-4e39-87d3-8e21a330ab48"),
                            TitleXPath = "//h1[@class='b-text__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("c38454ee-bc5a-4045-9924-7098e80f1976"),
                            DescriptionXPath = "//div[@class='b-material-body']/div/*[not(@class='b-material-incut-m-image')]",
                            SourceId = new Guid("2651f767-ffa8-48b8-a4cc-2b7b7fb68cd2"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("1a7ff9f2-4a8f-4138-857c-16e9873187db"),
                            DescriptionXPath = "//article/div[@class='news_text']",
                            SourceId = new Guid("2583f477-fce2-4fe5-a341-81e30883bc06"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("121162a8-6a7c-4e61-9e54-ef037e135a8d"),
                            DescriptionXPath = "//article/div[@class='article-content']/*[not(@class)]",
                            SourceId = new Guid("5e452802-0e39-404c-8ed8-f7b89590a713"),
                            TitleXPath = "//article/header/div[@class='article-head__title']/text()"
                        },
                        new
                        {
                            Id = new Guid("f40d9536-44e5-45cf-95a0-ed05a887ee19"),
                            DescriptionXPath = "//div[contains(@class, 'styles_bodyWrapper')]/div[not(@class)]",
                            SourceId = new Guid("dbbce0f9-e7bc-4b7f-aa77-6b5b8319ffad"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("d8bd2f21-e873-442f-bec7-c9a7930d2db1"),
                            DescriptionXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()>1]",
                            SourceId = new Guid("cbdf304c-d447-4297-a5d4-7261ada925de"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("7ad5cd9a-4de7-42d1-9d50-a705754196f5"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("14e6bb2d-d968-439d-a6d9-e817e215d1dc"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("beeb9b0d-f3c3-4051-9a83-ea8758fcf977"),
                            DescriptionXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']",
                            SourceId = new Guid("5a57967a-9ab6-48e6-8a13-87b706ae9b85"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("a69e9126-aa28-4fe5-a7bd-be9d6117938e"),
                            DescriptionXPath = "//div[@itemprop='articleBody']",
                            SourceId = new Guid("ce169d0d-96fb-4acb-9663-6d01117e7ea4"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("b59d6368-6740-4aed-af58-ae2f5383f88e"),
                            DescriptionXPath = "//article[@itemprop='articleBody']/*[not(name() = 'h1') and not(name() = 'aside') and not(name() = 'meta') and not(name() = 'link') and not(@itemprop)]",
                            SourceId = new Guid("ab9e4601-c959-407e-9ef2-58bc670d6152"),
                            TitleXPath = "//h1/text()"
                        },
                        new
                        {
                            Id = new Guid("38481a31-8043-454c-b720-49c4efb3aeef"),
                            DescriptionXPath = "//div[contains(@class, 'full-article')]/*[not(name()='h1') and not(name()='style') and not(name()='div')]",
                            SourceId = new Guid("2c7ef109-2d05-477e-941f-e0f5a937ad7b"),
                            TitleXPath = "//div[@class='title article-header']/text()"
                        },
                        new
                        {
                            Id = new Guid("bd5e633f-793a-44d7-bee4-6104660d8326"),
                            DescriptionXPath = "//div[@itemprop='articleBody']/*[not(name()='div')]",
                            SourceId = new Guid("9fdb31aa-50e3-42e2-b5e0-1a734d7a57bb"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ParseSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_settings_id");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_x_path");

                    b.HasKey("Id")
                        .HasName("pk_news_parse_sub_title_settings");

                    b.HasIndex("ParseSettingsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_parse_sub_title_settings_parse_settings_id");

                    b.ToTable("news_parse_sub_title_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e03c4986-061d-43b8-84e6-084fc1fbba2a"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("62b37a37-4fd7-4dbe-8b53-25e936db2e02"),
                            TitleXPath = "//h1[@class='article__second-title']/text()"
                        },
                        new
                        {
                            Id = new Guid("aeb67563-05f6-441f-a437-200e27a7e105"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("de1c0851-8bd0-42f4-adcb-c57c9f397cdb"),
                            TitleXPath = "//div[contains(@class, 'article__summary')]/text()"
                        },
                        new
                        {
                            Id = new Guid("243e40d4-416e-488e-af7e-7ad3936a1459"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("2428fc94-f50e-473d-b266-4d797fac1316"),
                            TitleXPath = "//h3/text()"
                        },
                        new
                        {
                            Id = new Guid("1dc5cf37-2008-4195-9dca-67e84017135d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("13c63e40-ce79-41e4-9b46-dcafe1cce434"),
                            TitleXPath = "//div[contains(@class, 'topic-body__title')]/text()"
                        },
                        new
                        {
                            Id = new Guid("ee8a486e-ad5f-47d3-a4b6-38e4e460f55e"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("3933a019-c0e5-4e34-a33e-9373cee6758a"),
                            TitleXPath = "//div[contains(@class, 'PageArticleContent_lead')]/text()"
                        },
                        new
                        {
                            Id = new Guid("86f85603-56af-4c36-bd28-51eaaf405845"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("048afc27-d220-4129-918b-d5a1e9989e21"),
                            TitleXPath = "//div[contains(@class, 'article__text')]/div[@class='article__text__overview']/span/text()"
                        },
                        new
                        {
                            Id = new Guid("2c6390fb-9d03-4fae-809e-f67af8767d5b"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("b2628384-b53c-4e6d-a380-f06b7fa40fa1"),
                            TitleXPath = "//header[@class='doc_header']/h2[@class='doc_header__subheader']/text()"
                        },
                        new
                        {
                            Id = new Guid("59903f24-bf76-4baf-95a5-f5d812322abf"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1199fb6e-d599-4e79-8fcf-c327e287c527"),
                            TitleXPath = "//div[@class='article__intro']/p/text()"
                        },
                        new
                        {
                            Id = new Guid("38fa98cb-0d8a-4b61-988c-85ad34ef58b3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("1a7ff9f2-4a8f-4138-857c-16e9873187db"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("78f26ba9-6ae7-4ed3-9b71-d339cfec903d"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("f40d9536-44e5-45cf-95a0-ed05a887ee19"),
                            TitleXPath = "//article//header//p[contains(@class, 'styles_subtitle')]/text()"
                        },
                        new
                        {
                            Id = new Guid("c6a008f0-48b8-4233-96ac-363b780fd72a"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("d8bd2f21-e873-442f-bec7-c9a7930d2db1"),
                            TitleXPath = "//div[contains(@class, 'article-entry')]//div[@class='js-mediator-article']/p[position()=1]/text()"
                        },
                        new
                        {
                            Id = new Guid("167fff8c-8c12-47b3-abdd-7997aa398612"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("7ad5cd9a-4de7-42d1-9d50-a705754196f5"),
                            TitleXPath = "//h4/text()"
                        },
                        new
                        {
                            Id = new Guid("79257204-b4e7-4087-a6c6-a225f8384f44"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("beeb9b0d-f3c3-4051-9a83-ea8758fcf977"),
                            TitleXPath = "//div[@class='container-fluid shifted']/p[@class='announce lead']/text()"
                        },
                        new
                        {
                            Id = new Guid("2e99158f-454e-4138-a07e-576894bb0ee3"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("a69e9126-aa28-4fe5-a7bd-be9d6117938e"),
                            TitleXPath = "//h2/text()"
                        },
                        new
                        {
                            Id = new Guid("ec2b073a-2122-43c2-be01-32af1c033720"),
                            IsRequired = false,
                            ParseSettingsId = new Guid("38481a31-8043-454c-b720-49c4efb3aeef"),
                            TitleXPath = "//h1/text()"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_pictures");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_pictures_news_id");

                    b.ToTable("news_pictures", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NewsSiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_site_url");

                    b.Property<string>("NewsUrlXPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("news_url_x_path");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_news_search_settings");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_search_settings_source_id");

                    b.ToTable("news_search_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("27cc2dbf-0d0a-4430-bef8-7bf0aaed474e"),
                            NewsSiteUrl = "https://ria.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'cell-list__item-link')]/@href",
                            SourceId = new Guid("16425339-cf3e-4837-8613-c6d08cd42ea6")
                        },
                        new
                        {
                            Id = new Guid("42c2f24e-da8e-4726-8ba1-8e81c8584cc1"),
                            NewsSiteUrl = "https://russian.rt.com/",
                            NewsUrlXPath = "//a[contains(@class, 'link') and contains(@href, 'news/')]/@href",
                            SourceId = new Guid("09ffcd85-9795-4f77-8e55-68d40e34d87a")
                        },
                        new
                        {
                            Id = new Guid("d9490955-73d7-4ccd-a12d-0298676ccf69"),
                            NewsSiteUrl = "https://tass.ru/",
                            NewsUrlXPath = "//a[contains(@class, 'tass_pkg_link-v5WdK') and contains(substring(@href, 2), '/')]/@href",
                            SourceId = new Guid("d74c7a85-d4a8-44bc-8c5f-bc5f71b60c75")
                        },
                        new
                        {
                            Id = new Guid("d16f631f-c864-4c60-a7f5-2e48f2b63f22"),
                            NewsSiteUrl = "https://lenta.ru/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/') or starts-with(@href, '/articles/')]/@href",
                            SourceId = new Guid("f882277e-6851-4590-bcb9-424a7751c1af")
                        },
                        new
                        {
                            Id = new Guid("83068fcd-f12d-424e-8ba1-7b4218ee34a9"),
                            NewsSiteUrl = "https://rg.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html')]/@href",
                            SourceId = new Guid("0e267466-ad14-4f7b-8b00-d278dc128fd7")
                        },
                        new
                        {
                            Id = new Guid("9029ac66-809d-4fa8-92ac-eb09a5593436"),
                            NewsSiteUrl = "https://aif.ru/",
                            NewsUrlXPath = "//span[contains(@class, 'item_text__title')]/../@href",
                            SourceId = new Guid("2eb0a1ad-38ed-4aa2-8a73-4d80f156f815")
                        },
                        new
                        {
                            Id = new Guid("3821fe2e-dd7b-475c-b53c-d1a89a0fe4b0"),
                            NewsSiteUrl = "https://www.rbc.ru/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.rbc.ru/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("98fac15c-fc17-4012-a827-cf12e4fc72fc")
                        },
                        new
                        {
                            Id = new Guid("da57a56d-f11e-4da3-993b-828934cf8953"),
                            NewsSiteUrl = "https://www.sports.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '.html#comments'))]/@href",
                            SourceId = new Guid("a6e56b29-cb95-428a-b676-1607db592bce")
                        },
                        new
                        {
                            Id = new Guid("8f276814-1da6-422b-b770-4970fea81243"),
                            NewsSiteUrl = "https://www.kommersant.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/doc/') and contains(@href, '?from=')]/@href",
                            SourceId = new Guid("f6f82166-9205-4978-b093-c39b66fab4f3")
                        },
                        new
                        {
                            Id = new Guid("dcbbc026-5b5d-466c-9d9a-19a30da14526"),
                            NewsSiteUrl = "https://iz.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '?main_click')]/@href",
                            SourceId = new Guid("ab6e74cd-405f-489f-8672-c8923c8fa9ec")
                        },
                        new
                        {
                            Id = new Guid("f5001665-65be-4778-bcf5-35d9074a6103"),
                            NewsSiteUrl = "https://tsargrad.tv/",
                            NewsUrlXPath = "//a[contains(@class, 'news-item__link')]/@href",
                            SourceId = new Guid("d8c2325c-a066-4d5f-a080-bc4a8086b9e4")
                        },
                        new
                        {
                            Id = new Guid("3dfe41ae-02c8-45e4-b187-21c49a44743e"),
                            NewsSiteUrl = "https://www.belta.by/",
                            NewsUrlXPath = "//a[contains(@href, 'https://www.belta.by/') and contains(@href, '/view/')]/@href",
                            SourceId = new Guid("a05bc4f7-d5bc-490b-8593-0171551c9958")
                        },
                        new
                        {
                            Id = new Guid("2a3106bb-a209-4322-bea4-63f4819ec3b2"),
                            NewsSiteUrl = "https://svpressa.ru/all/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(contains(@href, '?')) and not(starts-with(@href, '/all/news/'))]/@href",
                            SourceId = new Guid("f3759f29-9364-4e39-87d3-8e21a330ab48")
                        },
                        new
                        {
                            Id = new Guid("a256c76a-22ad-45ba-8cc2-f23be83d3fa0"),
                            NewsSiteUrl = "https://www.m24.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("2651f767-ffa8-48b8-a4cc-2b7b7fb68cd2")
                        },
                        new
                        {
                            Id = new Guid("9dd4cd23-9cdd-4444-adaf-75490c022b1a"),
                            NewsSiteUrl = "https://vz.ru/",
                            NewsUrlXPath = "//a[contains(@href, '.html') and not(contains(@href, '#comments')) and not(contains(@href, '?')) and not(contains(@href, '/about/'))]/@href",
                            SourceId = new Guid("2583f477-fce2-4fe5-a341-81e30883bc06")
                        },
                        new
                        {
                            Id = new Guid("5e84e942-114b-40ff-8a5a-da5148d61302"),
                            NewsSiteUrl = "https://www.championat.com/news/1.html?utm_source=button&utm_medium=news",
                            NewsUrlXPath = "//a[contains(@href, 'news-') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("5e452802-0e39-404c-8ed8-f7b89590a713")
                        },
                        new
                        {
                            Id = new Guid("77238363-0944-406f-a46e-ac690142d524"),
                            NewsSiteUrl = "https://life.ru/s/novosti",
                            NewsUrlXPath = "//a[contains(@href, '/p/')]/@href",
                            SourceId = new Guid("dbbce0f9-e7bc-4b7f-aa77-6b5b8319ffad")
                        },
                        new
                        {
                            Id = new Guid("6c5bb4da-4884-46ac-864c-4041e0ed042d"),
                            NewsSiteUrl = "https://3dnews.ru/news/",
                            NewsUrlXPath = "//div[@class='news-feed-all']//a[@class='entry-header']/h1/../@href",
                            SourceId = new Guid("cbdf304c-d447-4297-a5d4-7261ada925de")
                        },
                        new
                        {
                            Id = new Guid("ef50c26c-d074-4f3b-85aa-6a98e42df17e"),
                            NewsSiteUrl = "https://www.ixbt.com/news/",
                            NewsUrlXPath = "//a[starts-with(@href, '/news/') and contains(@href, '.html') and not(contains(@href, '#comments'))]/@href",
                            SourceId = new Guid("14e6bb2d-d968-439d-a6d9-e817e215d1dc")
                        },
                        new
                        {
                            Id = new Guid("df855cd6-bf2c-43a4-9dc7-e45467b93691"),
                            NewsSiteUrl = "https://ixbt.games/news/",
                            NewsUrlXPath = "//a[@class='card-link']/@href",
                            SourceId = new Guid("5a57967a-9ab6-48e6-8a13-87b706ae9b85")
                        },
                        new
                        {
                            Id = new Guid("6c5f313d-75d3-4a86-9ba4-efe4ff2a041d"),
                            NewsSiteUrl = "https://www.gazeta.ru/news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and contains(@href, '.shtml') and not(contains(@href, '?'))]/@href",
                            SourceId = new Guid("ce169d0d-96fb-4acb-9663-6d01117e7ea4")
                        },
                        new
                        {
                            Id = new Guid("782facc0-bc10-48b4-80d5-b00325abab27"),
                            NewsSiteUrl = "https://www.interfax.ru/",
                            NewsUrlXPath = "//div[@class='timeline']//a[@tabindex=5]/@href",
                            SourceId = new Guid("ab9e4601-c959-407e-9ef2-58bc670d6152")
                        },
                        new
                        {
                            Id = new Guid("22905a11-43f0-486e-84cc-9fd43327c74a"),
                            NewsSiteUrl = "https://www.pravda.ru/",
                            NewsUrlXPath = "//a[contains(@href, '/news/') and not(@href='https://www.pravda.ru/news/')]/@href",
                            SourceId = new Guid("2c7ef109-2d05-477e-941f-e0f5a937ad7b")
                        },
                        new
                        {
                            Id = new Guid("b15433b1-2042-483d-8f4d-275b9a8cd607"),
                            NewsSiteUrl = "https://ura.news/",
                            NewsUrlXPath = "//a[contains(@href, '/news/')]/@href",
                            SourceId = new Guid("9fdb31aa-50e3-42e2-b5e0-1a734d7a57bb")
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sources");

                    b.HasIndex("Title", "SiteUrl")
                        .HasDatabaseName("ix_news_sources_title_site_url");

                    b.ToTable("news_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("16425339-cf3e-4837-8613-c6d08cd42ea6"),
                            SiteUrl = "https://ria.ru/",
                            Title = "РИА Новости"
                        },
                        new
                        {
                            Id = new Guid("09ffcd85-9795-4f77-8e55-68d40e34d87a"),
                            SiteUrl = "https://russian.rt.com/",
                            Title = "RT на русском"
                        },
                        new
                        {
                            Id = new Guid("d74c7a85-d4a8-44bc-8c5f-bc5f71b60c75"),
                            SiteUrl = "https://tass.ru/",
                            Title = "ТАСС"
                        },
                        new
                        {
                            Id = new Guid("f882277e-6851-4590-bcb9-424a7751c1af"),
                            SiteUrl = "https://lenta.ru/",
                            Title = "Лента.Ру"
                        },
                        new
                        {
                            Id = new Guid("0e267466-ad14-4f7b-8b00-d278dc128fd7"),
                            SiteUrl = "https://rg.ru/",
                            Title = "Российская газета"
                        },
                        new
                        {
                            Id = new Guid("2eb0a1ad-38ed-4aa2-8a73-4d80f156f815"),
                            SiteUrl = "https://aif.ru/",
                            Title = "Аргументы и факты"
                        },
                        new
                        {
                            Id = new Guid("98fac15c-fc17-4012-a827-cf12e4fc72fc"),
                            SiteUrl = "https://www.rbc.ru/",
                            Title = "РБК"
                        },
                        new
                        {
                            Id = new Guid("a6e56b29-cb95-428a-b676-1607db592bce"),
                            SiteUrl = "https://www.sports.ru/",
                            Title = "Storts.ru"
                        },
                        new
                        {
                            Id = new Guid("f6f82166-9205-4978-b093-c39b66fab4f3"),
                            SiteUrl = "https://www.kommersant.ru/",
                            Title = "Коммерсантъ"
                        },
                        new
                        {
                            Id = new Guid("ab6e74cd-405f-489f-8672-c8923c8fa9ec"),
                            SiteUrl = "https://iz.ru/",
                            Title = "Известия"
                        },
                        new
                        {
                            Id = new Guid("d8c2325c-a066-4d5f-a080-bc4a8086b9e4"),
                            SiteUrl = "https://tsargrad.tv/",
                            Title = "Царьград"
                        },
                        new
                        {
                            Id = new Guid("a05bc4f7-d5bc-490b-8593-0171551c9958"),
                            SiteUrl = "https://www.belta.by/",
                            Title = "БелТА"
                        },
                        new
                        {
                            Id = new Guid("f3759f29-9364-4e39-87d3-8e21a330ab48"),
                            SiteUrl = "https://svpressa.ru/",
                            Title = "СвободнаяПресса"
                        },
                        new
                        {
                            Id = new Guid("2651f767-ffa8-48b8-a4cc-2b7b7fb68cd2"),
                            SiteUrl = "https://www.m24.ru/",
                            Title = "Москва 24"
                        },
                        new
                        {
                            Id = new Guid("2583f477-fce2-4fe5-a341-81e30883bc06"),
                            SiteUrl = "https://vz.ru/",
                            Title = "ВЗГЛЯД.РУ"
                        },
                        new
                        {
                            Id = new Guid("5e452802-0e39-404c-8ed8-f7b89590a713"),
                            SiteUrl = "https://www.championat.com/",
                            Title = "Чемпионат.com"
                        },
                        new
                        {
                            Id = new Guid("dbbce0f9-e7bc-4b7f-aa77-6b5b8319ffad"),
                            SiteUrl = "https://life.ru/",
                            Title = "Life"
                        },
                        new
                        {
                            Id = new Guid("cbdf304c-d447-4297-a5d4-7261ada925de"),
                            SiteUrl = "https://3dnews.ru/",
                            Title = "3Dnews.ru"
                        },
                        new
                        {
                            Id = new Guid("14e6bb2d-d968-439d-a6d9-e817e215d1dc"),
                            SiteUrl = "https://www.ixbt.com/",
                            Title = "iXBT.com"
                        },
                        new
                        {
                            Id = new Guid("5a57967a-9ab6-48e6-8a13-87b706ae9b85"),
                            SiteUrl = "https://ixbt.games/",
                            Title = "iXBT.games"
                        },
                        new
                        {
                            Id = new Guid("ce169d0d-96fb-4acb-9663-6d01117e7ea4"),
                            SiteUrl = "https://www.gazeta.ru/",
                            Title = "Газета.Ru"
                        },
                        new
                        {
                            Id = new Guid("ab9e4601-c959-407e-9ef2-58bc670d6152"),
                            SiteUrl = "https://www.interfax.ru/",
                            Title = "Интерфакс"
                        },
                        new
                        {
                            Id = new Guid("2c7ef109-2d05-477e-941f-e0f5a937ad7b"),
                            SiteUrl = "https://www.pravda.ru/",
                            Title = "Правда.ру"
                        },
                        new
                        {
                            Id = new Guid("9fdb31aa-50e3-42e2-b5e0-1a734d7a57bb"),
                            SiteUrl = "https://ura.news/",
                            Title = "Ura.ru"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_source_logos");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_source_logos_source_id");

                    b.ToTable("news_source_logos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96db53de-f002-4e78-9872-f1286c51cc08"),
                            SourceId = new Guid("5a57967a-9ab6-48e6-8a13-87b706ae9b85"),
                            Url = "https://sun13-2.userapi.com/s/v1/ig2/_ID-2w6Llad8ig5_987dKAfh1pyLdj7HfLHqGx9HxyDjoEDN7wxR0ZWJm5ja1Ey6UuQXaEYEBW1Zd51cpRrjSGfS.jpg?size=100x100&quality=96&crop=22,22,626,626&ava=1"
                        });
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_sub_titles");

                    b.HasIndex("NewsId")
                        .IsUnique()
                        .HasDatabaseName("ix_news_sub_titles_news_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_news_sub_titles_title");

                    b.ToTable("news_sub_titles", (string)null);
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", "Editor")
                        .WithMany("News")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_news_editors_editor_id");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Description")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsDescription", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_descriptions_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithMany("Editors")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_editors_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseEditorSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseEditorSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_editor_settings_news_parse_settings_parse_settin");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePictureSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePictureSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_picture_settings_news_parse_settings_parse_setti");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParsePublishedAtSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParsePublishedAtSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_published_at_settings_news_parse_settings_parse_");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("ParseSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", "ParseSettings")
                        .WithOne("ParseSubTitleSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSubTitleSettings", "ParseSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_parse_sub_title_settings_news_parse_settings_parse_set");

                    b.Navigation("ParseSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("Picture")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsPicture", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_pictures_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("SearchSettings")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSearchSettings", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_search_settings_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", "Source")
                        .WithOne("Logo")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSourceLogo", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_source_logos_news_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", b =>
                {
                    b.HasOne("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", "News")
                        .WithOne("SubTitle")
                        .HasForeignKey("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSubTitle", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_sub_titles_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.News", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Picture");

                    b.Navigation("SubTitle");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsEditor", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsParseSettings", b =>
                {
                    b.Navigation("ParseEditorSettings");

                    b.Navigation("ParsePictureSettings");

                    b.Navigation("ParsePublishedAtSettings");

                    b.Navigation("ParseSubTitleSettings");
                });

            modelBuilder.Entity("NewsAggregator.News.Databases.EntityFramework.News.Entities.NewsSource", b =>
                {
                    b.Navigation("Editors");

                    b.Navigation("Logo");

                    b.Navigation("ParseSettings");

                    b.Navigation("SearchSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
