version: "3.6"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./docker-data/kibana:/usr/share/kibana/data
    depends_on:
      - elasticsearch