version: "3.6"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-data/portainer_data:/data
    ports:
      - 9000:9000