version: "3.6"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=sa
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"