name: Docker Release Images Build

on:
  push:
    tags:
      - 'v*' 

jobs:
  newsaggregator-gateways-api-build:
    name: newsaggregator-gateways-api image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Gateways/NewsAggregator.Gateways.Api
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-gateways-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}
  
  newsaggregator-news-api-build:
    name: newsaggregator-news-api image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Services/News/NewsAggregator.News.Api
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-news-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}
  
  newsaggregator-news-mvc-build:
    name: newsaggregator-news-mvc image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Services/News/NewsAggregator.News.Mvc
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-news-mvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}
  
  newsaggregator-news-parser-build:
    name: newsaggregator-news-parser image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Services/News/NewsAggregator.News.Parser
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-news-parser
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}
  
  newsaggregator-news-searcher-build:
    name: newsaggregator-news-searcher image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Services/News/NewsAggregator.News.Searcher
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-news-searcher
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}
  
  newsaggregator-notification-api-build:
    name: newsaggregator-notification-api image build, pull and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_SRC_DIR: src/Microservices/Services/Notification/NewsAggregator.Notification.Api
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/newsaggregator/newsaggregator-notification-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE:${{ github.ref }} .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE:${{ github.ref }}