name: NewsUrlsParser Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  news-urls-parser-unit-test:
    name: NewsUrlsParser unit test
    runs-on: ubuntu-latest
    env:
      ProjectName: ./src/Microservices/Services/News/NewsAggregator.News.Tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET

        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $ProjectName

      - name: Build
        run: dotnet build $ProjectName --no-restore

      - name: Test
        run: dotnet test $ProjectName --no-build -l "console;verbosity=normal" --filter "FullyQualifiedName=NewsAggregator.News.Tests.Services.Parsers.NewsUrlsParserTests.ParseAsync_EachNewsSource_ReturnNotEmptyResult"